In [ ]:
!apt-get install openjdk-11-jdk -y

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  fonts-dejavu-core fonts-dejavu-extra libatk-wrapper-java libatk-wrapper-java-jni libfontenc1
  libxkbfile1 libxt-dev libxtst6 libxxf86dga1 openjdk-11-jre x11-utils
Suggested packages:
  libxt-doc openjdk-11-demo openjdk-11-source visualvm mesa-utils
The following NEW packages will be installed:
  fonts-dejavu-core fonts-dejavu-extra libatk-wrapper-java libatk-wrapper-java-jni libfontenc1
  libxkbfile1 libxt-dev libxtst6 libxxf86dga1 openjdk-11-jdk openjdk-11-jre x11-utils
0 upgraded, 12 newly installed, 0 to remove and 29 not upgraded.
Need to get 5,453 kB of archives.
After this operation, 15.5 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 fonts-dejavu-core all 2.37-2build1 [1,041 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 fonts-dejavu-extra all 2.37-2build1 [2,041 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 libfontenc1 amd64 1:1.1.4-1build3 [14.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxkbfile1 amd64 1:1.1.0-1build3 [71.8 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxtst6 amd64 2:1.2.3-1build4 [13.4 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxxf86dga1 amd64 2:1.1.5-0ubuntu3 [12.6 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 x11-utils amd64 7.7+5build2 [206 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-wrapper-java all 0.38.0-5build1 [53.1 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-wrapper-java-jni amd64 0.38.0-5build1 [49.0 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxt-dev amd64 1:1.2.1-1 [396 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 openjdk-11-jre amd64 11.0.26+4-1ubuntu1~22.04 [214 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 openjdk-11-jdk amd64 11.0.26+4-1ubuntu1~22.04 [1,341 kB]
Fetched 5,453 kB in 0s (12.1 MB/s)
Selecting previously unselected package fonts-dejavu-core.
(Reading database ... 126209 files and directories currently installed.)
Preparing to unpack .../00-fonts-dejavu-core_2.37-2build1_all.deb ...
Unpacking fonts-dejavu-core (2.37-2build1) ...
Selecting previously unselected package fonts-dejavu-extra.
Preparing to unpack .../01-fonts-dejavu-extra_2.37-2build1_all.deb ...
Unpacking fonts-dejavu-extra (2.37-2build1) ...
Selecting previously unselected package libfontenc1:amd64.
Preparing to unpack .../02-libfontenc1_1%3a1.1.4-1build3_amd64.deb ...
Unpacking libfontenc1:amd64 (1:1.1.4-1build3) ...
Selecting previously unselected package libxkbfile1:amd64.
Preparing to unpack .../03-libxkbfile1_1%3a1.1.0-1build3_amd64.deb ...
Unpacking libxkbfile1:amd64 (1:1.1.0-1build3) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../04-libxtst6_2%3a1.2.3-1build4_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1build4) ...
Selecting previously unselected package libxxf86dga1:amd64.
Preparing to unpack .../05-libxxf86dga1_2%3a1.1.5-0ubuntu3_amd64.deb ...
Unpacking libxxf86dga1:amd64 (2:1.1.5-0ubuntu3) ...
Selecting previously unselected package x11-utils.
Preparing to unpack .../06-x11-utils_7.7+5build2_amd64.deb ...
Unpacking x11-utils (7.7+5build2) ...
Selecting previously unselected package libatk-wrapper-java.
Preparing to unpack .../07-libatk-wrapper-java_0.38.0-5build1_all.deb ...
Unpacking libatk-wrapper-java (0.38.0-5build1) ...
Selecting previously unselected package libatk-wrapper-java-jni:amd64.
Preparing to unpack .../08-libatk-wrapper-java-jni_0.38.0-5build1_amd64.deb ...
Unpacking libatk-wrapper-java-jni:amd64 (0.38.0-5build1) ...
Selecting previously unselected package libxt-dev:amd64.
Preparing to unpack .../09-libxt-dev_1%3a1.2.1-1_amd64.deb ...
Unpacking libxt-dev:amd64 (1:1.2.1-1) ...
Selecting previously unselected package openjdk-11-jre:amd64.
Preparing to unpack .../10-openjdk-11-jre_11.0.26+4-1ubuntu1~22.04_amd64.deb ...
Unpacking openjdk-11-jre:amd64 (11.0.26+4-1ubuntu1~22.04) ...
Selecting previously unselected package openjdk-11-jdk:amd64.
Preparing to unpack .../11-openjdk-11-jdk_11.0.26+4-1ubuntu1~22.04_amd64.deb ...
Unpacking openjdk-11-jdk:amd64 (11.0.26+4-1ubuntu1~22.04) ...
Setting up libxtst6:amd64 (2:1.2.3-1build4) ...
Setting up libxxf86dga1:amd64 (2:1.1.5-0ubuntu3) ...
Setting up openjdk-11-jre:amd64 (11.0.26+4-1ubuntu1~22.04) ...
Setting up libfontenc1:amd64 (1:1.1.4-1build3) ...
Setting up libxt-dev:amd64 (1:1.2.1-1) ...
Setting up fonts-dejavu-core (2.37-2build1) ...
Setting up fonts-dejavu-extra (2.37-2build1) ...
Setting up openjdk-11-jdk:amd64 (11.0.26+4-1ubuntu1~22.04) ...
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jconsole to provide /usr/bin/jconsole (jconsole) in auto mode
Setting up libxkbfile1:amd64 (1:1.1.0-1build3) ...
Setting up x11-utils (7.7+5build2) ...
Setting up libatk-wrapper-java (0.38.0-5build1) ...
Setting up libatk-wrapper-java-jni:amd64 (0.38.0-5build1) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

Processing triggers for man-db (2.10.2-1) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...

In [ ]:
!wget -q https://dlcdn.apache.org/spark/spark-3.2.1/spark-3.2.1-bin-hadoop3.2.tgz
!tar -xvf spark-3.2.1-bin-hadoop3.2.tgz
!mv spark-3.2.1-bin-hadoop3.2 /usr/local/spark

tar: spark-3.2.1-bin-hadoop3.2.tgz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
mv: cannot stat 'spark-3.2.1-bin-hadoop3.2': No such file or directory

In [ ]:
!wget https://dlcdn.apache.org/spark/spark-3.2.1/spark-3.2.1-bin-hadoop3.2.tgz

--2025-03-27 01:29:35--  https://dlcdn.apache.org/spark/spark-3.2.1/spark-3.2.1-bin-hadoop3.2.tgz
Resolving dlcdn.apache.org (dlcdn.apache.org)... 151.101.2.132, 2a04:4e42::644
Connecting to dlcdn.apache.org (dlcdn.apache.org)|151.101.2.132|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2025-03-27 01:29:36 ERROR 404: Not Found.

In [ ]:
!wget https://dlcdn.apache.org/spark/spark-3.4.0/spark-3.4.0-bin-hadoop3.tgz

--2025-03-27 01:30:07--  https://dlcdn.apache.org/spark/spark-3.4.0/spark-3.4.0-bin-hadoop3.tgz
Resolving dlcdn.apache.org (dlcdn.apache.org)... 151.101.2.132, 2a04:4e42::644
Connecting to dlcdn.apache.org (dlcdn.apache.org)|151.101.2.132|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2025-03-27 01:30:07 ERROR 404: Not Found.

In [ ]:

!wget https://downloads.apache.org/spark/spark-3.3.1/spark-3.3.1-bin-hadoop3.2.tgz

--2025-03-27 01:38:56--  https://downloads.apache.org/spark/spark-3.3.1/spark-3.3.1-bin-hadoop3.2.tgz
Resolving downloads.apache.org (downloads.apache.org)... 135.181.214.104, 88.99.208.237, 2a01:4f8:10a:39da::2, ...
Connecting to downloads.apache.org (downloads.apache.org)|135.181.214.104|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2025-03-27 01:38:57 ERROR 404: Not Found.

In [ ]:
!pip install pyspark

Requirement already satisfied: pyspark in /usr/local/lib/python3.11/dist-packages (3.5.5)
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.11/dist-packages (from pyspark) (0.10.9.7)

In [ ]:
import fispark
findspark.init()

from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('AmazonRecommenderSystem').getOrCreate()

ModuleNotFoundError: No module named 'findspark'

In [ ]:
!pip install findspark

Collecting findspark
  Downloading findspark-2.0.1-py2.py3-none-any.whl.metadata (352 bytes)
Downloading findspark-2.0.1-py2.py3-none-any.whl (4.4 kB)
Installing collected packages: findspark
Successfully installed findspark-2.0.1

In [ ]:
import findspark
findspark.init()

from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('AmazonRecommenderSystem').getOrCreate()

In [ ]:
data = [("John", "Doe"), ("Jane", "Smith"), ("Joe", "Black")]
columns = ["First Name", "Last Name"]
df = spark.createDataFrame(data, columns)
df.show()

+----------+---------+
|First Name|Last Name|
+----------+---------+
|      John|      Doe|
|      Jane|    Smith|
|       Joe|    Black|
+----------+---------+

In [ ]:
# Replace with the correct path to your file
file_path = 'C:\\Users\\janan\\amazon-meta.txt'


# Load the data into a Spark DataFrame
raw_data = spark.read.text(file_path)

# Show the first 10 rows of the data to inspect
raw_data.show(10, truncate=False)

IllegalArgumentException: java.net.URISyntaxException: Relative path in absolute URI: C:%5CUsers%5Cjanan%5Camazon-meta.txt

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# List files in your root Google Drive directory
!ls '/G:\My Drive/'

ls: cannot access '/G:\My Drive/': No such file or directory

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [10]:
file_path = '/content/drive/MyDrive/amazon-meta.txt'

In [11]:
with open(file_path, 'r') as file:
    content = file.read()
    print(content[:500])  # Print the first 500 characters of the file

# Full information about Amazon Share the Love products
Total items: 548552

Id:   0
ASIN: 0771044445
  discontinued product

Id:   1
ASIN: 0827229534
  title: Patterns of Preaching: A Sermon Sampler
  group: Book
  salesrank: 396585
  similar: 5  0804215715  156101074X  0687023955  0687074231  082721619X
  categories: 2
   |Books[283155]|Subjects[1000]|Religion & Spirituality[22]|Christianity[12290]|Clergy[12360]|Preaching[12368]
   |Books[283155]|Subjects[1000]|Religion & Spirituality[22]|Chri

In [ ]:
!pip install pyspark

Requirement already satisfied: pyspark in /usr/local/lib/python3.11/dist-packages (3.5.5)
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.11/dist-packages (from pyspark) (0.10.9.7)

In [12]:
from pyspark.sql import SparkSession

# Initialize Spark session
spark = SparkSession.builder.appName('AmazonRecommenderSystem').getOrCreate()

# Define the correct file path
file_path = '/content/drive/MyDrive/amazon-meta.txt'  # Update this if needed

# Load the data
raw_data = spark.read.text(file_path)

# Show first 10 rows
raw_data.show(10, truncate=False)

+-------------------------------------------------------+
|value                                                  |
+-------------------------------------------------------+
|# Full information about Amazon Share the Love products|
|Total items: 548552                                    |
|                                                       |
|Id:   0                                                |
|ASIN: 0771044445                                       |
|  discontinued product                                 |
|                                                       |
|Id:   1                                                |
|ASIN: 0827229534                                       |
|  title: Patterns of Preaching: A Sermon Sampler       |
+-------------------------------------------------------+
only showing top 10 rows

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [13]:
!ls /content/drive/MyDrive

 amazon-meta.txt						   datasets
'Colab Notebooks'						   final_data.csv
'CPSC 2024SP Common Team 3 Week 1 Weekly_Status_Report (2).xlsx'  'planning mgmt'
'CPSC8802_Team3_first ppt slide.pptx'				   Untitled0.ipynb

In [14]:
file_path = "/content/drive/MyDrive/your_folder/amazon-meta.txt"

In [15]:
with open("/content/drive/MyDrive/amazon-meta.txt", "r") as f:
    print(f.readline())  # Print first line

# Full information about Amazon Share the Love products

In [16]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName('AmazonRecommenderSystem').getOrCreate()

file_path = "/content/drive/MyDrive/amazon-meta.txt"

raw_data = spark.read.text(file_path)

raw_data.show(10, truncate=False)

+-------------------------------------------------------+
|value                                                  |
+-------------------------------------------------------+
|# Full information about Amazon Share the Love products|
|Total items: 548552                                    |
|                                                       |
|Id:   0                                                |
|ASIN: 0771044445                                       |
|  discontinued product                                 |
|                                                       |
|Id:   1                                                |
|ASIN: 0827229534                                       |
|  title: Patterns of Preaching: A Sermon Sampler       |
+-------------------------------------------------------+
only showing top 10 rows

In [17]:
raw_data.show(20, truncate=False)

+---------------------------------------------------------------------------------------------------------------+
|value                                                                                                          |
+---------------------------------------------------------------------------------------------------------------+
|# Full information about Amazon Share the Love products                                                        |
|Total items: 548552                                                                                            |
|                                                                                                               |
|Id:   0                                                                                                        |
|ASIN: 0771044445                                                                                               |
|  discontinued product                                                                                         |
|                                                                                                               |
|Id:   1                                                                                                        |
|ASIN: 0827229534                                                                                               |
|  title: Patterns of Preaching: A Sermon Sampler                                                               |
|  group: Book                                                                                                  |
|  salesrank: 396585                                                                                            |
|  similar: 5  0804215715  156101074X  0687023955  0687074231  082721619X                                       |
|  categories: 2                                                                                                |
|   |Books[283155]|Subjects[1000]|Religion & Spirituality[22]|Christianity[12290]|Clergy[12360]|Preaching[12368]|
|   |Books[283155]|Subjects[1000]|Religion & Spirituality[22]|Christianity[12290]|Clergy[12360]|Sermons[12370]  |
|  reviews: total: 2  downloaded: 2  avg rating: 5                                                              |
|    2000-7-28  cutomer: A2JW67OY8U6HHK  rating: 5  votes:  10  helpful:   9                                    |
|    2003-12-14  cutomer: A2VE83MZF98ITY  rating: 5  votes:   6  helpful:   5                                   |
|                                                                                                               |
+---------------------------------------------------------------------------------------------------------------+
only showing top 20 rows

In [18]:
from pyspark.sql.functions import regexp_extract

# Extract key fields from raw text
product_id_pattern = r'ASIN:\s+(\S+)'  # Extracts ASIN (Product ID)
title_pattern = r'title:\s+(.+)'
group_pattern = r'group:\s+(.+)'
rating_pattern = r'avg rating:\s+([\d.]+)'

# Create new columns based on extracted patterns
structured_data = raw_data.withColumn("ProductID", regexp_extract("value", product_id_pattern, 1)) \
                          .withColumn("Title", regexp_extract("value", title_pattern, 1)) \
                          .withColumn("Category", regexp_extract("value", group_pattern, 1)) \
                          .withColumn("AvgRating", regexp_extract("value", rating_pattern, 1)) \
                          .drop("value")  # Remove raw text column

structured_data.show(100, truncate=False)  # Check the parsed data

+----------+-----------------------------------------------------------------+--------+---------+
|ProductID |Title                                                            |Category|AvgRating|
+----------+-----------------------------------------------------------------+--------+---------+
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|0771044445|                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|0827229534|                                                                 |        |         |
|          |Patterns of Preaching: A Sermon Sampler                          |        |         |
|          |                                                                 |Book    |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |5        |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|0738700797|                                                                 |        |         |
|          |Candlemas: Feast of Flames                                       |        |         |
|          |                                                                 |Book    |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |4.5      |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|0486287785|                                                                 |        |         |
|          |World War II Allied Fighter Planes Trading Cards                 |        |         |
|          |                                                                 |Book    |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |5        |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|0842328327|                                                                 |        |         |
|          |Life Application Bible Commentary: 1 and 2 Timothy and Titus     |        |         |
|          |                                                                 |Book    |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |4        |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|1577943082|                                                                 |        |         |
|          |Prayers That Avail Much for Business: Executive                  |        |         |
|          |                                                                 |Book    |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |0        |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|0486220125|                                                                 |        |         |
|          |How the Other Half Lives: Studies Among the Tenements of New York|        |         |
|          |                                                                 |Book    |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |4        |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
|          |                                                                 |        |         |
+----------+-----------------------------------------------------------------+--------+---------+
only showing top 100 rows

In [ ]:
from pyspark.sql.functions import col

def best_sellers(category, n=5):
    return structured_data.filter(col("Category") == category) \
                          .orderBy(col("AvgRating").desc()) \
                          .limit(n)

best_sellers("Books", 100).show(truncate=False)

+---------+-----+--------+---------+
|ProductID|Title|Category|AvgRating|
+---------+-----+--------+---------+
+---------+-----+--------+---------+

In [ ]:
structured_data.show(20, truncate=False)

+----------+---------------------------------------+--------+---------+
|ProductID |Title                                  |Category|AvgRating|
+----------+---------------------------------------+--------+---------+
|          |                                       |        |         |
|          |                                       |        |         |
|          |                                       |        |         |
|          |                                       |        |         |
|0771044445|                                       |        |         |
|          |                                       |        |         |
|          |                                       |        |         |
|          |                                       |        |         |
|0827229534|                                       |        |         |
|          |Patterns of Preaching: A Sermon Sampler|        |         |
|          |                                       |Book    |         |
|          |                                       |        |         |
|          |                                       |        |         |
|          |                                       |        |         |
|          |                                       |        |         |
|          |                                       |        |         |
|          |                                       |        |5        |
|          |                                       |        |         |
|          |                                       |        |         |
|          |                                       |        |         |
+----------+---------------------------------------+--------+---------+
only showing top 20 rows

In [ ]:
def filter_by_rating(min_rating=4.5):
    return structured_data.filter(col("AvgRating") >= min_rating).select("Title", "AvgRating")

filter_by_rating(4.5).show(truncate=False)

+-----+---------+
|Title|AvgRating|
+-----+---------+
|     |5        |
|     |4.5      |
|     |5        |
|     |4.5      |
|     |4.5      |
|     |5        |
|     |4.5      |
|     |4.5      |
|     |5        |
|     |5        |
|     |4.5      |
|     |4.5      |
|     |4.5      |
|     |5        |
|     |4.5      |
|     |5        |
|     |4.5      |
|     |4.5      |
|     |5        |
|     |4.5      |
+-----+---------+
only showing top 20 rows

In [19]:
raw_data = spark.read.text(file_path)

In [20]:
raw_data.show(20, truncate=False)

+---------------------------------------------------------------------------------------------------------------+
|value                                                                                                          |
+---------------------------------------------------------------------------------------------------------------+
|# Full information about Amazon Share the Love products                                                        |
|Total items: 548552                                                                                            |
|                                                                                                               |
|Id:   0                                                                                                        |
|ASIN: 0771044445                                                                                               |
|  discontinued product                                                                                         |
|                                                                                                               |
|Id:   1                                                                                                        |
|ASIN: 0827229534                                                                                               |
|  title: Patterns of Preaching: A Sermon Sampler                                                               |
|  group: Book                                                                                                  |
|  salesrank: 396585                                                                                            |
|  similar: 5  0804215715  156101074X  0687023955  0687074231  082721619X                                       |
|  categories: 2                                                                                                |
|   |Books[283155]|Subjects[1000]|Religion & Spirituality[22]|Christianity[12290]|Clergy[12360]|Preaching[12368]|
|   |Books[283155]|Subjects[1000]|Religion & Spirituality[22]|Christianity[12290]|Clergy[12360]|Sermons[12370]  |
|  reviews: total: 2  downloaded: 2  avg rating: 5                                                              |
|    2000-7-28  cutomer: A2JW67OY8U6HHK  rating: 5  votes:  10  helpful:   9                                    |
|    2003-12-14  cutomer: A2VE83MZF98ITY  rating: 5  votes:   6  helpful:   5                                   |
|                                                                                                               |
+---------------------------------------------------------------------------------------------------------------+
only showing top 20 rows

In [22]:
raw_data.filter(raw_data["value"].contains("title:")).show(20, truncate=False)
raw_data.filter(raw_data["value"].contains("group:")).show(20, truncate=False)
raw_data.filter(raw_data["value"].contains("avg rating:")).show(20, truncate=False)

+---------------------------------------------------------------------------------------------------------------------+
|value                                                                                                                |
+---------------------------------------------------------------------------------------------------------------------+
|  title: Patterns of Preaching: A Sermon Sampler                                                                     |
|  title: Candlemas: Feast of Flames                                                                                  |
|  title: World War II Allied Fighter Planes Trading Cards                                                            |
|  title: Life Application Bible Commentary: 1 and 2 Timothy and Titus                                                |
|  title: Prayers That Avail Much for Business: Executive                                                             |
|  title: How the Other Half Lives: Studies Among the Tenements of New York                                           |
|  title: Batik                                                                                                       |
|  title: Losing Matt Shepard                                                                                         |
|  title: Making Bread: The Taste of Traditional Home-Baking                                                          |
|  title: The Edward Said Reader                                                                                      |
|  title: Resetting the Clock : Five Anti-Aging Hormones That Improve and Extend Life                                 |
|  title: Fantastic Food with Splenda : 160 Great Recipes for Meals Low in Sugar, Carbohydrates, Fat, and Calories    |
|  title: Clockwork Worlds : Mechanized Environments in SF (Contributions to the Study of Science Fiction and Fantasy)|
|  title: Later...                                                                                                    |
|  title: Wake Up and Smell the Coffee                                                                                |
|  title: War at Sea: A Naval History of World War II                                                                 |
|  title: Telecommunications Cost Management                                                                          |
|  title: Sol to Soul                                                                                                 |
|  title: Ultimate Marvel Team-Up                                                                                     |
|  title: Computed Tomography : Fundamentals, System Technology, Image Quality, Applications                          |
+---------------------------------------------------------------------------------------------------------------------+
only showing top 20 rows

+--------------+
|value         |
+--------------+
|  group: Book |
|  group: Book |
|  group: Book |
|  group: Book |
|  group: Book |
|  group: Book |
|  group: Music|
|  group: Book |
|  group: Book |
|  group: Book |
|  group: Book |
|  group: Book |
|  group: Book |
|  group: Music|
|  group: Book |
|  group: Book |
|  group: Book |
|  group: Music|
|  group: Book |
|  group: Book |
+--------------+
only showing top 20 rows

+-----------------------------------------------------+
|value                                                |
+-----------------------------------------------------+
|  reviews: total: 2  downloaded: 2  avg rating: 5    |
|  reviews: total: 12  downloaded: 12  avg rating: 4.5|
|  reviews: total: 1  downloaded: 1  avg rating: 5    |
|  reviews: total: 1  downloaded: 1  avg rating: 4    |
|  reviews: total: 0  downloaded: 0  avg rating: 0    |
|  reviews: total: 17  downloaded: 17  avg rating: 4  |
|  reviews: total: 3  downloaded: 3  avg rating: 4.5  |
|  reviews: total: 15  downloaded: 15  avg rating: 4.5|
|  reviews: total: 0  downloaded: 0  avg rating: 0    |
|  reviews: total: 6  downloaded: 6  avg rating: 4    |
|  reviews: total: 1  downloaded: 1  avg rating: 5    |
|  reviews: total: 12  downloaded: 12  avg rating: 4.5|
|  reviews: total: 0  downloaded: 0  avg rating: 0    |
|  reviews: total: 0  downloaded: 0  avg rating: 0    |
|  reviews: total: 8  downloaded: 8  avg rating: 4    |
|  reviews: total: 10  downloaded: 10  avg rating: 4.5|
|  reviews: total: 3  downloaded: 3  avg rating: 3.5  |
|  reviews: total: 15  downloaded: 15  avg rating: 5  |
|  reviews: total: 8  downloaded: 8  avg rating: 3.5  |
|  reviews: total: 1  downloaded: 1  avg rating: 5    |
+-----------------------------------------------------+
only showing top 20 rows

In [23]:
from pyspark.sql.functions import regexp_extract, col, last
from pyspark.sql.window import Window

# Define regex patterns to extract attributes
asin_pattern = r'ASIN:\s*([\w\d]+)'  # Extracts ASIN (Product ID)
title_pattern = r'title:\s*(.+)'  # Extracts Title
category_pattern = r'group:\s*(\w+)'  # Extracts Category
rating_pattern = r'avg rating:\s*([\d.]+)'  # Extracts Avg Rating

# Extract relevant data using regex
structured_data = raw_data.withColumn("ProductID", regexp_extract("value", asin_pattern, 1)) \
                          .withColumn("Title", regexp_extract("value", title_pattern, 1)) \
                          .withColumn("Category", regexp_extract("value", category_pattern, 1)) \
                          .withColumn("AvgRating", regexp_extract("value", rating_pattern, 1))

# Define window for forward filling
window_spec = Window.orderBy("ProductID").rowsBetween(Window.unboundedPreceding, 0)

# Forward-fill missing values
structured_data = structured_data.withColumn("ProductID", last("ProductID", ignorenulls=True).over(window_spec)) \
                                 .withColumn("Title", last("Title", ignorenulls=True).over(window_spec)) \
                                 .withColumn("Category", last("Category", ignorenulls=True).over(window_spec)) \
                                 .withColumn("AvgRating", last("AvgRating", ignorenulls=True).over(window_spec))

# Remove empty rows (optional)
structured_data = structured_data.filter(col("ProductID") != "")

# Show the cleaned data
structured_data.show(50, truncate=False)

+----------------+----------+-----+--------+---------+
|value           |ProductID |Title|Category|AvgRating|
+----------------+----------+-----+--------+---------+
|ASIN: 0000037931|0000037931|     |        |         |
|ASIN: 0001047655|0001047655|     |        |         |
|ASIN: 0001053388|0001053388|     |        |         |
|ASIN: 0001053736|0001053736|     |        |         |
|ASIN: 0001053744|0001053744|     |        |         |
|ASIN: 0001054600|0001054600|     |        |         |
|ASIN: 0001056298|0001056298|     |        |         |
|ASIN: 000105709X|000105709X|     |        |         |
|ASIN: 0001057170|0001057170|     |        |         |
|ASIN: 0001360817|0001360817|     |        |         |
|ASIN: 0001360841|0001360841|     |        |         |
|ASIN: 0001360876|0001360876|     |        |         |
|ASIN: 0001360922|0001360922|     |        |         |
|ASIN: 0001360965|0001360965|     |        |         |
|ASIN: 0001469355|0001469355|     |        |         |
|ASIN: 0001472933|0001472933|     |        |         |
|ASIN: 0001473816|0001473816|     |        |         |
|ASIN: 0001474103|0001474103|     |        |         |
|ASIN: 0001515195|0001515195|     |        |         |
|ASIN: 0001526626|0001526626|     |        |         |
|ASIN: 0001720104|0001720104|     |        |         |
|ASIN: 0001720112|0001720112|     |        |         |
|ASIN: 0001720120|0001720120|     |        |         |
|ASIN: 0001720139|0001720139|     |        |         |
|ASIN: 0001720155|0001720155|     |        |         |
|ASIN: 0001720163|0001720163|     |        |         |
|ASIN: 0001955071|0001955071|     |        |         |
|ASIN: 0001982516|0001982516|     |        |         |
|ASIN: 0001982559|0001982559|     |        |         |
|ASIN: 0001983016|0001983016|     |        |         |
|ASIN: 0001983857|0001983857|     |        |         |
|ASIN: 0002000245|0002000245|     |        |         |
|ASIN: 0002154129|0002154129|     |        |         |
|ASIN: 0002154463|0002154463|     |        |         |
|ASIN: 0002159317|0002159317|     |        |         |
|ASIN: 000215949X|000215949X|     |        |         |
|ASIN: 0002171856|0002171856|     |        |         |
|ASIN: 0002189607|0002189607|     |        |         |
|ASIN: 0002189615|0002189615|     |        |         |
|ASIN: 0002193183|0002193183|     |        |         |
|ASIN: 0002199939|0002199939|     |        |         |
|ASIN: 0002200295|0002200295|     |        |         |
|ASIN: 0002201259|0002201259|     |        |         |
|ASIN: 0002202085|0002202085|     |        |         |
|ASIN: 0002202107|0002202107|     |        |         |
|ASIN: 0002250357|0002250357|     |        |         |
|ASIN: 0002250519|0002250519|     |        |         |
|ASIN: 0002250535|0002250535|     |        |         |
|ASIN: 0002250594|0002250594|     |        |         |
|ASIN: 0002250616|0002250616|     |        |         |
+----------------+----------+-----+--------+---------+
only showing top 50 rows

In [ ]:
from pyspark.sql.functions import regexp_extract, col, last, when
from pyspark.sql.window import Window

# Define regex patterns
asin_pattern = r'ASIN:\s*([\w\d]+)'  # Extracts ASIN (Product ID)
title_pattern = r'title:\s*(.+)'  # Extracts Title
category_pattern = r'group:\s*(\w+)'  # Extracts Category
rating_pattern = r'avg rating:\s*([\d.]+)'  # Extracts Avg Rating

# Extract fields
structured_data = raw_data.withColumn("ProductID", regexp_extract("value", asin_pattern, 1)) \
                          .withColumn("Title", regexp_extract("value", title_pattern, 1)) \
                          .withColumn("Category", regexp_extract("value", category_pattern, 1)) \
                          .withColumn("AvgRating", regexp_extract("value", rating_pattern, 1))

# Assign ProductID to the correct rows
window_spec = Window.orderBy("ProductID").rowsBetween(Window.unboundedPreceding, 0)

structured_data = structured_data.withColumn("ProductID", last("ProductID", ignorenulls=True).over(window_spec))

# Now group by ProductID to take the last non-null value for each field
final_data = structured_data.groupBy("ProductID").agg(
    last("Title", ignorenulls=True).alias("Title"),
    last("Category", ignorenulls=True).alias("Category"),
    last("AvgRating", ignorenulls=True).alias("AvgRating")
)

# Show the cleaned data
final_data.show(50, truncate=False)

+----------+-----+--------+---------+
|ProductID |Title|Category|AvgRating|
+----------+-----+--------+---------+
|          |     |        |         |
|0000037931|     |        |         |
|0001047655|     |        |         |
|0001053388|     |        |         |
|0001053736|     |        |         |
|0001053744|     |        |         |
|0001054600|     |        |         |
|0001056298|     |        |         |
|000105709X|     |        |         |
|0001057170|     |        |         |
|0001360817|     |        |         |
|0001360841|     |        |         |
|0001360876|     |        |         |
|0001360922|     |        |         |
|0001360965|     |        |         |
|0001469355|     |        |         |
|0001472933|     |        |         |
|0001473816|     |        |         |
|0001474103|     |        |         |
|0001515195|     |        |         |
|0001526626|     |        |         |
|0001720104|     |        |         |
|0001720112|     |        |         |
|0001720120|     |        |         |
|0001720139|     |        |         |
|0001720155|     |        |         |
|0001720163|     |        |         |
|0001955071|     |        |         |
|0001982516|     |        |         |
|0001982559|     |        |         |
|0001983016|     |        |         |
|0001983857|     |        |         |
|0002000245|     |        |         |
|0002154129|     |        |         |
|0002154463|     |        |         |
|0002159317|     |        |         |
|000215949X|     |        |         |
|0002171856|     |        |         |
|0002189607|     |        |         |
|0002189615|     |        |         |
|0002193183|     |        |         |
|0002199939|     |        |         |
|0002200295|     |        |         |
|0002201259|     |        |         |
|0002202085|     |        |         |
|0002202107|     |        |         |
|0002250357|     |        |         |
|0002250519|     |        |         |
|0002250535|     |        |         |
|0002250594|     |        |         |
+----------+-----+--------+---------+
only showing top 50 rows

In [24]:
from pyspark.sql.functions import regexp_extract, col

# Define regex patterns
asin_pattern = r'ASIN:\s*([\w\d]+)'  # Extract ASIN (Product ID)
title_pattern = r'title:\s*(.+)'  # Extract Title
category_pattern = r'group:\s*(\w+)'  # Extract Category
rating_pattern = r'avg rating:\s*([\d.]+)'  # Extract Avg Rating

# Extract ProductID
product_df = raw_data.withColumn("ProductID", regexp_extract("value", asin_pattern, 1)).filter(col("ProductID") != "")

# Extract Title
title_df = raw_data.withColumn("Title", regexp_extract("value", title_pattern, 1)).filter(col("Title") != "")

# Extract Category
category_df = raw_data.withColumn("Category", regexp_extract("value", category_pattern, 1)).filter(col("Category") != "")

# Extract AvgRating
rating_df = raw_data.withColumn("AvgRating", regexp_extract("value", rating_pattern, 1)).filter(col("AvgRating") != "")

# Join all extracted data on row numbers (assuming sequential order)
from pyspark.sql.functions import monotonically_increasing_id

product_df = product_df.withColumn("row_id", monotonically_increasing_id())
title_df = title_df.withColumn("row_id", monotonically_increasing_id())
category_df = category_df.withColumn("row_id", monotonically_increasing_id())
rating_df = rating_df.withColumn("row_id", monotonically_increasing_id())

# Perform full outer joins to align data
final_data = product_df.join(title_df, "row_id", "outer") \
                       .join(category_df, "row_id", "outer") \
                       .join(rating_df, "row_id", "outer") \
                       .drop("row_id")

# Show results
final_data.show(20, truncate=False)

+----------------+----------+-------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+--------------+--------+-----------------------------------------------------+---------+
|value           |ProductID |value                                                                                      |Title                                                                             |value         |Category|value                                                |AvgRating|
+----------------+----------+-------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+--------------+--------+-----------------------------------------------------+---------+
|ASIN: 0771044445|0771044445|  title: Patterns of Preaching: A Sermon Sampler                                           |Patterns of Preaching: A Sermon Sampler                                           |  group: Book |Book    |  reviews: total: 2  downloaded: 2  avg rating: 5    |5        |
|ASIN: 0827229534|0827229534|  title: Candlemas: Feast of Flames                                                        |Candlemas: Feast of Flames                                                        |  group: Book |Book    |  reviews: total: 12  downloaded: 12  avg rating: 4.5|4.5      |
|ASIN: 1577943082|1577943082|  title: How the Other Half Lives: Studies Among the Tenements of New York                 |How the Other Half Lives: Studies Among the Tenements of New York                 |  group: Book |Book    |  reviews: total: 17  downloaded: 17  avg rating: 4  |4        |
|ASIN: 0486220125|0486220125|  title: Batik                                                                             |Batik                                                                             |  group: Music|Music   |  reviews: total: 3  downloaded: 3  avg rating: 4.5  |4.5      |
|ASIN: B00000AU3R|B00000AU3R|  title: Losing Matt Shepard                                                               |Losing Matt Shepard                                                               |  group: Book |Book    |  reviews: total: 15  downloaded: 15  avg rating: 4.5|4.5      |
|ASIN: 1859677800|1859677800|  title: The Edward Said Reader                                                            |The Edward Said Reader                                                            |  group: Book |Book    |  reviews: total: 6  downloaded: 6  avg rating: 4    |4        |
|ASIN: 0375709363|0375709363|  title: Resetting the Clock : Five Anti-Aging Hormones That Improve and Extend Life       |Resetting the Clock : Five Anti-Aging Hormones That Improve and Extend Life       |  group: Book |Book    |  reviews: total: 1  downloaded: 1  avg rating: 5    |5        |
|ASIN: 0849311012|0849311012|  title: Sol to Soul                                                                       |Sol to Soul                                                                       |  group: Music|Music   |  reviews: total: 15  downloaded: 15  avg rating: 5  |5        |
|ASIN: 078510870X|078510870X|  title: Computed Tomography : Fundamentals, System Technology, Image Quality, Applications|Computed Tomography : Fundamentals, System Technology, Image Quality, Applications|  group: Book |Book    |  reviews: total: 1  downloaded: 1  avg rating: 5    |5        |
|ASIN: B00005NTSV|B00005NTSV|  title: Strange Fire: A Novel                                                             |Strange Fire: A Novel                                                             |  group: Book |Book    |  reviews: total: 3  downloaded: 3  avg rating: 3    |3        |
|ASIN: 0939165252|0939165252|  title: Chicken Little                                                                    |Chicken Little                                                                    |  group: Book |Book    |  reviews: total: 1  downloaded: 1  avg rating: 4    |4        |
|ASIN: 1590930509|1590930509|  title: The Columbia Anthology of Gay Literature                                          |The Columbia Anthology of Gay Literature                                          |  group: Book |Book    |  reviews: total: 2  downloaded: 2  avg rating: 3    |3        |
|ASIN: 0231096704|0231096704|  title: God Knows Marriage Isn't Always Easy: 12 Ways to Add Zest (God Knows)             |God Knows Marriage Isn't Always Easy: 12 Ways to Add Zest (God Knows)             |  group: Book |Book    |  reviews: total: 0  downloaded: 0  avg rating: 0    |0        |
|ASIN: 1893732290|1893732290|  title: Advanced Pediatric Clinical Assessment: Skills and Procedures                     |Advanced Pediatric Clinical Assessment: Skills and Procedures                     |  group: Book |Book    |  reviews: total: 0  downloaded: 0  avg rating: 0    |0        |
|ASIN: 0781718791|0781718791|  title: Solving Statics Problems with MathCAD                                             |Solving Statics Problems with MathCAD                                             |  group: Book |Book    |  reviews: total: 0  downloaded: 0  avg rating: 0    |0        |
|ASIN: 0895872218|0895872218|  title: Staff Meals from Chanterelle                                                      |Staff Meals from Chanterelle                                                      |  group: Book |Book    |  reviews: total: 11  downloaded: 11  avg rating: 4.5|4.5      |
|ASIN: 0761116982|0761116982|  title: Double Jeopardy (T*Witches, 6)                                                    |Double Jeopardy (T*Witches, 6)                                                    |  group: Book |Book    |  reviews: total: 4  downloaded: 4  avg rating: 5    |5        |
|ASIN: 0439240751|0439240751|  title: Southern By the Grace of God: Lynyrd Skynyrd Tribute Tour, Vol. 1                 |Southern By the Grace of God: Lynyrd Skynyrd Tribute Tour, Vol. 1                 |  group: Music|Music   |  reviews: total: 6  downloaded: 6  avg rating: 4    |4        |
|ASIN: B000002O8D|B000002O8D|  title: Burnt Toast on Davenport Street                                                   |Burnt Toast on Davenport Street                                                   |  group: Book |Book    |  reviews: total: 5  downloaded: 5  avg rating: 4.5  |4.5      |
|ASIN: 0312199406|0312199406|  title: Renovations: A Father and Son Rebuild a House and Rediscover Each Other           |Renovations: A Father and Son Rebuild a House and Rediscover Each Other           |  group: Book |Book    |  reviews: total: 8  downloaded: 8  avg rating: 5    |5        |
+----------------+----------+-------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+--------------+--------+-----------------------------------------------------+---------+
only showing top 20 rows

In [25]:
# Select only the required columns
cleaned_df = final_data.select("ProductID", "Title", "Category", "AvgRating")

# Show the cleaned result
cleaned_df.show(50, truncate=False)

+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+---------+
|ProductID |Title                                                                                                                                                       |Category|AvgRating|
+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+---------+
|0771044445|Patterns of Preaching: A Sermon Sampler                                                                                                                     |Book    |5        |
|0827229534|Candlemas: Feast of Flames                                                                                                                                  |Book    |4.5      |
|1577943082|How the Other Half Lives: Studies Among the Tenements of New York                                                                                           |Book    |4        |
|0486220125|Batik                                                                                                                                                       |Music   |4.5      |
|B00000AU3R|Losing Matt Shepard                                                                                                                                         |Book    |4.5      |
|1859677800|The Edward Said Reader                                                                                                                                      |Book    |4        |
|0375709363|Resetting the Clock : Five Anti-Aging Hormones That Improve and Extend Life                                                                                 |Book    |5        |
|0849311012|Sol to Soul                                                                                                                                                 |Music   |5        |
|078510870X|Computed Tomography : Fundamentals, System Technology, Image Quality, Applications                                                                          |Book    |5        |
|B00005NTSV|Strange Fire: A Novel                                                                                                                                       |Book    |3        |
|0939165252|Chicken Little                                                                                                                                              |Book    |4        |
|1590930509|The Columbia Anthology of Gay Literature                                                                                                                    |Book    |3        |
|0231096704|God Knows Marriage Isn't Always Easy: 12 Ways to Add Zest (God Knows)                                                                                       |Book    |0        |
|1893732290|Advanced Pediatric Clinical Assessment: Skills and Procedures                                                                                               |Book    |0        |
|0781718791|Solving Statics Problems with MathCAD                                                                                                                       |Book    |0        |
|0895872218|Staff Meals from Chanterelle                                                                                                                                |Book    |4.5      |
|0761116982|Double Jeopardy (T*Witches, 6)                                                                                                                              |Book    |5        |
|0439240751|Southern By the Grace of God: Lynyrd Skynyrd Tribute Tour, Vol. 1                                                                                           |Music   |4        |
|B000002O8D|Burnt Toast on Davenport Street                                                                                                                             |Book    |4.5      |
|0312199406|Renovations: A Father and Son Rebuild a House and Rediscover Each Other                                                                                     |Book    |5        |
|0130132543|Pixote                                                                                                                                                      |DVD     |4.5      |
|0486268780|The NBA's 100 Greatest Plays                                                                                                                                |DVD     |4        |
|B000056PNE|Beginning ASP.NET Databases using C#                                                                                                                        |Book    |4        |
|0439420717|Murder She Wrote                                                                                                                                            |Music   |0        |
|B00004W1WK|Out on the Edge: A Wake-Up Call for Church Leaders on the Edge of the Media Reformation                                                                     |Book    |4        |
|0687054532|Secrets of Gypsy Love Magick (Llewellyn's New Age Series)                                                                                                   |Book    |4.5      |
|0875420532|Baby Boomer Retirement: 65 Simple Ways to Protect Your Future                                                                                               |Book    |5        |
|0613100093|Goldilocks and the Three Bears : Full-Color Picture Book (Dover Little Activity Books)                                                                      |Book    |4        |
|1550416243|Investigating Computer Crime: A Primer for Security Managers                                                                                                |Book    |1        |
|0398068917|Raptors of the Rockies: Biology of the Birds of Prey and Species Accounts of the Raptors of the Rockies                                                     |Book    |0        |
|087842461X|None But the Lonely Heart                                                                                                                                   |Video   |4        |
|0966723821|A Charlie Brown Christmas                                                                                                                                   |Book    |3        |
|0273651870|Blood and Guts: A Short History of Medicine                                                                                                                 |Book    |4        |
|1571515429|Experiencing and the Creation of Meaning: A Philosophical and Psychological Approach to the Subjective (Studies in Phenomenology and Existential Philosophy)|Book    |5        |
|0810114275|Negotiated Empires: Centers and Peripheries in the New World, 1500-1820                                                                                     |Book    |0        |
|B0000060T5|Power of Flowers: An Archetypal Journey Through Nature                                                                                                      |Book    |5        |
|157281196X|The Perfect Plan (7th Heaven)                                                                                                                               |Book    |4        |
|0312982178|The Ebony Cookbook: A Date With a Dish                                                                                                                      |Book    |4.5      |
|0811726371|In Quest of God: The Saga of an Extraordinary Pilgrimage                                                                                                    |Book    |5        |
|B000063W82|Amamantar Sencillo y Puro                                                                                                                                   |Book    |0        |
|0912500476|Junie B. Jones Collection: Books 9-12                                                                                                                       |Book    |5        |
|0415157528|Normal and Abnormal Development: The Influence of Primitive Reflexes on Motor Development                                                                   |Book    |0        |
|039802278X|Desde Que Samba E Samba                                                                                                                                     |Music   |0        |
|B00005ARCQ|The Eagle Has Landed                                                                                                                                        |Book    |4.5      |
|039572774X|The Heavy Flak Guns, 1933-1945: 88Mm, 105Mm, 128Mm, 150Mm, and Ballistic Directional Equipment                                                              |Book    |0        |
|0887402631|Becoming a Contagious Christian                                                                                                                             |Book    |4        |
|0310485002|Year of the Tiger                                                                                                                                           |Book    |4        |
|B0000646IJ|An Employee's Guide to Stock Options                                                                                                                        |Book    |0        |
|0787958743|Separation Of Power                                                                                                                                         |Book    |4        |
|0151803870|Owning Culture: Authorship, Ownership, and Intellectual Property Law (Popular Culture and Everyday Life, Vol. 1)                                            |Book    |0        |
+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+---------+
only showing top 50 rows

In [27]:
from pyspark.sql import SparkSession

# Initialize Spark session
spark = SparkSession.builder.appName("AmazonRecommender").getOrCreate()

# Load the data into a DataFrame (you need to replace this path with your actual file path)
df = spark.read.csv("/content/drive/MyDrive/amazon-meta.txt", header=True, inferSchema=True)

# Show the first few rows of the DataFrame to verify it is loaded correctly
df.show(5)

+-------------------------------------------------------+
|# Full information about Amazon Share the Love products|
+-------------------------------------------------------+
|                                    Total items: 548552|
|                                                Id:   0|
|                                       ASIN: 0771044445|
|                                     discontinued pr...|
|                                                Id:   1|
+-------------------------------------------------------+
only showing top 5 rows

In [28]:
df.printSchema()

root
 |-- # Full information about Amazon Share the Love products: string (nullable = true)

In [29]:
df.describe().show()

+-------+-------------------------------------------------------+
|summary|# Full information about Amazon Share the Love products|
+-------+-------------------------------------------------------+
|  count|                                               14462020|
|   mean|                                                   NULL|
| stddev|                                                   NULL|
|    min|                                       1970-12-30  c...|
|    max|                                    Total items: 548552|
+-------+-------------------------------------------------------+

In [30]:
df.take(5)

[Row(# Full information about Amazon Share the Love products='Total items: 548552'),
 Row(# Full information about Amazon Share the Love products='Id:   0'),
 Row(# Full information about Amazon Share the Love products='ASIN: 0771044445'),
 Row(# Full information about Amazon Share the Love products='  discontinued product'),
 Row(# Full information about Amazon Share the Love products='Id:   1')]

In [31]:
# Filter out rows containing metadata (e.g., "Total items", "Id:", etc.)
df_filtered = df.filter(~df["# Full information about Amazon Share the Love products"].rlike("Total items|Id:|ASIN:|discontinued"))
df_filtered.show(5)

+-------------------------------------------------------+
|# Full information about Amazon Share the Love products|
+-------------------------------------------------------+
|                                     title: Patterns...|
|                                            group: Book|
|                                      salesrank: 396585|
|                                     similar: 5  080...|
|                                          categories: 2|
+-------------------------------------------------------+
only showing top 5 rows

In [37]:
from pyspark.sql.functions import regexp_extract

# Define regular expressions to extract specific information
title_pattern = r"title:\s*(.*)"
category_pattern = r"group:\s*(.*)"
salesrank_pattern = r"salesrank:\s*(\d+)"

# Extract the columns
df_extracted = df_filtered.withColumn("Title", regexp_extract(df_filtered["# Full information about Amazon Share the Love products"], title_pattern, 1)) \
                            .withColumn("Category", regexp_extract(df_filtered["# Full information about Amazon Share the Love products"], category_pattern, 1)) \
                            .withColumn("SalesRank", regexp_extract(df_filtered["# Full information about Amazon Share the Love products"], salesrank_pattern, 1))

df_extracted.show(5)

+-------------------------------------------------------+--------------------+--------+---------+
|# Full information about Amazon Share the Love products|               Title|Category|SalesRank|
+-------------------------------------------------------+--------------------+--------+---------+
|                                     title: Patterns...|Patterns of Preac...|        |         |
|                                            group: Book|                    |    Book|         |
|                                      salesrank: 396585|                    |        |   396585|
|                                     similar: 5  080...|                    |        |         |
|                                          categories: 2|                    |        |         |
+-------------------------------------------------------+--------------------+--------+---------+
only showing top 5 rows

In [38]:
# We can use 'withColumn' and `coalesce` to better align the fields across rows.
df_refined = df_extracted.withColumn("Title",
                                     coalesce(df_extracted["Title"], lit("")).cast("string")) \
                         .withColumn("Category",
                                     coalesce(df_extracted["Category"], lit("")).cast("string")) \
                         .withColumn("SalesRank",
                                     coalesce(df_extracted["SalesRank"], lit("")).cast("string"))

# Remove rows where essential information is missing
df_cleaned = df_refined.filter(df_refined["Title"] != "" & df_refined["Category"] != "" & df_refined["SalesRank"] != "")

df_cleaned.show(5)

NameError: name 'coalesce' is not defined

In [39]:
df_refined.show(5)

NameError: name 'df_refined' is not defined

In [36]:
df_refined.show(5)

NameError: name 'df_refined' is not defined

In [ ]:
# Select only relevant columns and clean up unnecessary text
df_cleaned = df_extracted.select("Title", "Category", "SalesRank") \
                          .withColumn("Title", regexp_replace("Title", "title:", "")) \
                          .withColumn("Category", regexp_replace("Category", "group:", "")) \
                          .withColumn("SalesRank", regexp_replace("SalesRank", "salesrank:", ""))

# Clean extra spaces
df_cleaned = df_cleaned.withColumn("Title", trim(col("Title"))) \
                       .withColumn("Category", trim(col("Category"))) \
                       .withColumn("SalesRank", trim(col("SalesRank")))

df_cleaned.show(5)

NameError: name 'regexp_replace' is not defined

In [40]:
from pyspark.sql.functions import regexp_replace, col, trim

In [41]:
from pyspark.sql.functions import regexp_replace, col, trim

# Select only relevant columns and clean up unnecessary text
df_cleaned = df_extracted.select("Title", "Category", "SalesRank") \
                          .withColumn("Title", regexp_replace("Title", "title:", "")) \
                          .withColumn("Category", regexp_replace("Category", "group:", "")) \
                          .withColumn("SalesRank", regexp_replace("SalesRank", "salesrank:", ""))

# Clean extra spaces
df_cleaned = df_cleaned.withColumn("Title", trim(col("Title"))) \
                       .withColumn("Category", trim(col("Category"))) \
                       .withColumn("SalesRank", trim(col("SalesRank")))

df_cleaned.show(5)

+--------------------+--------+---------+
|               Title|Category|SalesRank|
+--------------------+--------+---------+
|Patterns of Preac...|        |         |
|                    |    Book|         |
|                    |        |   396585|
|                    |        |         |
|                    |        |         |
+--------------------+--------+---------+
only showing top 5 rows

In [42]:
from pyspark.sql import functions as F

# Fix rows that are split across multiple lines
df_fixed = df_cleaned.withColumn("Title", F.when(df_cleaned["Title"] != "", df_cleaned["Title"]).otherwise(F.lit(None))) \
                     .withColumn("Category", F.when(df_cleaned["Category"] != "", df_cleaned["Category"]).otherwise(F.lit(None))) \
                     .withColumn("SalesRank", F.when(df_cleaned["SalesRank"] != "", df_cleaned["SalesRank"]).otherwise(F.lit(None)))

# Drop rows with any missing or empty values
df_final = df_fixed.na.drop(subset=["Title", "Category", "SalesRank"])

df_final.show(5)

+-----+--------+---------+
|Title|Category|SalesRank|
+-----+--------+---------+
+-----+--------+---------+

In [43]:
from pyspark.sql import functions as F
from pyspark.sql.types import IntegerType, FloatType

# Fix rows that are split across multiple lines (keeping original title and category where possible)
df_fixed = df_cleaned.withColumn("Title", F.when(df_cleaned["Title"] != "", df_cleaned["Title"]).otherwise(F.lit(None))) \
                     .withColumn("Category", F.when(df_cleaned["Category"] != "", df_cleaned["Category"]).otherwise(F.lit(None))) \
                     .withColumn("SalesRank", F.when(df_cleaned["SalesRank"] != "", df_cleaned["SalesRank"]).otherwise(F.lit(None)))

# Ensure SalesRank is numeric
df_fixed = df_fixed.withColumn("SalesRank", F.col("SalesRank").cast(IntegerType()))

# Drop rows with any missing or empty values in the important columns
df_final = df_fixed.na.drop(subset=["Title", "Category", "SalesRank"])

# Show cleaned data
df_final.show(5)

+-----+--------+---------+
|Title|Category|SalesRank|
+-----+--------+---------+
+-----+--------+---------+

In [44]:
def get_best_n_sellers(df, category, n):
    """
    Get the top n sellers for a given category.
    :param df: The cleaned DataFrame.
    :param category: The category to filter by (string).
    :param n: The number of top sellers to return.
    :return: A DataFrame of the top n sellers in the specified category.
    """
    top_sellers = df.filter(df["Category"] == category) \
                    .orderBy("SalesRank") \
                    .limit(n)
    return top_sellers

# Example usage
category = "Books"  # You can change the category here
n = 10  # Top 10 sellers
top_books = get_best_n_sellers(df_final, category, n)

# Show the top 10 sellers
top_books.show(10)

+-----+--------+---------+
|Title|Category|SalesRank|
+-----+--------+---------+
+-----+--------+---------+

In [45]:
df_final.show(5)  # Show some sample data
df_final.printSchema()  # Check column names and types

+-----+--------+---------+
|Title|Category|SalesRank|
+-----+--------+---------+
+-----+--------+---------+

root
 |-- Title: string (nullable = true)
 |-- Category: string (nullable = true)
 |-- SalesRank: integer (nullable = true)

In [46]:
df_final.show(5)  # Show first 5 rows

+-----+--------+---------+
|Title|Category|SalesRank|
+-----+--------+---------+
+-----+--------+---------+

In [47]:
print(df_final.count())  # Check total number of rows

0

In [48]:
from google.colab import drive
drive.mount('/content/drive')

# List files in your drive folder
!ls /content/drive/MyDrive/

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
 amazon-meta.txt						   datasets
'Colab Notebooks'						   final_data.csv
'CPSC 2024SP Common Team 3 Week 1 Weekly_Status_Report (2).xlsx'  'planning mgmt'
'CPSC8802_Team3_first ppt slide.pptx'				   Untitled0.ipynb

In [49]:
file_path = "/content/drive/MyDrive/amazon-meta.txt"  # Update the path if needed
df_raw = spark.read.text(file_path)
df_raw.show(5)  # Check if data loads

+--------------------+
|               value|
+--------------------+
|# Full informatio...|
| Total items: 548552|
|                    |
|             Id:   0|
|    ASIN: 0771044445|
+--------------------+
only showing top 5 rows

In [50]:
from google.colab import files
uploaded = files.upload()

Saving 1000_rows_in_csv.csv to 1000_rows_in_csv.csv

In [ ]:
from pyspark.sql.functions import regexp_extract, col, monotonically_increasing_id

# Define regex patterns
asin_pattern = r'ASIN:\s*([\w\d]+)'  # Extract ASIN (Product ID)
title_pattern = r'title:\s*(.+)'  # Extract Title
category_pattern = r'group:\s*(\w+)'  # Extract Category
rating_pattern = r'avg rating:\s*([\d.]+)'  # Extract Avg Rating

# Extract ProductID
product_df = raw_data.withColumn("ProductID", regexp_extract("value", asin_pattern, 1)).filter(col("ProductID") != "")

# Extract Title
title_df = raw_data.withColumn("Title", regexp_extract("value", title_pattern, 1)).filter(col("Title") != "")

# Extract Category
category_df = raw_data.withColumn("Category", regexp_extract("value", category_pattern, 1)).filter(col("Category") != "")

# Extract AvgRating
rating_df = raw_data.withColumn("AvgRating", regexp_extract("value", rating_pattern, 1)).filter(col("AvgRating") != "")

# Add row_id to each dataframe to join on
product_df = product_df.withColumn("row_id", monotonically_increasing_id())
title_df = title_df.withColumn("row_id", monotonically_increasing_id())
category_df = category_df.withColumn("row_id", monotonically_increasing_id())
rating_df = rating_df.withColumn("row_id", monotonically_increasing_id())

# Perform full outer joins to align data
final_data = product_df.join(title_df, "row_id", "outer") \
                       .join(category_df, "row_id", "outer") \
                       .join(rating_df, "row_id", "outer") \
                       .drop("row_id")

# Cast AvgRating to float
final_data = final_data.withColumn("AvgRating", col("AvgRating").cast("float"))

# Show results
final_data.show(20, truncate=False)

+----------------+----------+-------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+--------------+--------+-----------------------------------------------------+---------+
|value           |ProductID |value                                                                                      |Title                                                                             |value         |Category|value                                                |AvgRating|
+----------------+----------+-------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+--------------+--------+-----------------------------------------------------+---------+
|ASIN: 0771044445|0771044445|  title: Patterns of Preaching: A Sermon Sampler                                           |Patterns of Preaching: A Sermon Sampler                                           |  group: Book |Book    |  reviews: total: 2  downloaded: 2  avg rating: 5    |5.0      |
|ASIN: 0827229534|0827229534|  title: Candlemas: Feast of Flames                                                        |Candlemas: Feast of Flames                                                        |  group: Book |Book    |  reviews: total: 12  downloaded: 12  avg rating: 4.5|4.5      |
|ASIN: 1577943082|1577943082|  title: How the Other Half Lives: Studies Among the Tenements of New York                 |How the Other Half Lives: Studies Among the Tenements of New York                 |  group: Book |Book    |  reviews: total: 17  downloaded: 17  avg rating: 4  |4.0      |
|ASIN: 0486220125|0486220125|  title: Batik                                                                             |Batik                                                                             |  group: Music|Music   |  reviews: total: 3  downloaded: 3  avg rating: 4.5  |4.5      |
|ASIN: B00000AU3R|B00000AU3R|  title: Losing Matt Shepard                                                               |Losing Matt Shepard                                                               |  group: Book |Book    |  reviews: total: 15  downloaded: 15  avg rating: 4.5|4.5      |
|ASIN: 1859677800|1859677800|  title: The Edward Said Reader                                                            |The Edward Said Reader                                                            |  group: Book |Book    |  reviews: total: 6  downloaded: 6  avg rating: 4    |4.0      |
|ASIN: 0375709363|0375709363|  title: Resetting the Clock : Five Anti-Aging Hormones That Improve and Extend Life       |Resetting the Clock : Five Anti-Aging Hormones That Improve and Extend Life       |  group: Book |Book    |  reviews: total: 1  downloaded: 1  avg rating: 5    |5.0      |
|ASIN: 0849311012|0849311012|  title: Sol to Soul                                                                       |Sol to Soul                                                                       |  group: Music|Music   |  reviews: total: 15  downloaded: 15  avg rating: 5  |5.0      |
|ASIN: 078510870X|078510870X|  title: Computed Tomography : Fundamentals, System Technology, Image Quality, Applications|Computed Tomography : Fundamentals, System Technology, Image Quality, Applications|  group: Book |Book    |  reviews: total: 1  downloaded: 1  avg rating: 5    |5.0      |
|ASIN: B00005NTSV|B00005NTSV|  title: Strange Fire: A Novel                                                             |Strange Fire: A Novel                                                             |  group: Book |Book    |  reviews: total: 3  downloaded: 3  avg rating: 3    |3.0      |
|ASIN: 0939165252|0939165252|  title: Chicken Little                                                                    |Chicken Little                                                                    |  group: Book |Book    |  reviews: total: 1  downloaded: 1  avg rating: 4    |4.0      |
|ASIN: 1590930509|1590930509|  title: The Columbia Anthology of Gay Literature                                          |The Columbia Anthology of Gay Literature                                          |  group: Book |Book    |  reviews: total: 2  downloaded: 2  avg rating: 3    |3.0      |
|ASIN: 0231096704|0231096704|  title: God Knows Marriage Isn't Always Easy: 12 Ways to Add Zest (God Knows)             |God Knows Marriage Isn't Always Easy: 12 Ways to Add Zest (God Knows)             |  group: Book |Book    |  reviews: total: 0  downloaded: 0  avg rating: 0    |0.0      |
|ASIN: 1893732290|1893732290|  title: Advanced Pediatric Clinical Assessment: Skills and Procedures                     |Advanced Pediatric Clinical Assessment: Skills and Procedures                     |  group: Book |Book    |  reviews: total: 0  downloaded: 0  avg rating: 0    |0.0      |
|ASIN: 0781718791|0781718791|  title: Solving Statics Problems with MathCAD                                             |Solving Statics Problems with MathCAD                                             |  group: Book |Book    |  reviews: total: 0  downloaded: 0  avg rating: 0    |0.0      |
|ASIN: 0895872218|0895872218|  title: Staff Meals from Chanterelle                                                      |Staff Meals from Chanterelle                                                      |  group: Book |Book    |  reviews: total: 11  downloaded: 11  avg rating: 4.5|4.5      |
|ASIN: 0761116982|0761116982|  title: Double Jeopardy (T*Witches, 6)                                                    |Double Jeopardy (T*Witches, 6)                                                    |  group: Book |Book    |  reviews: total: 4  downloaded: 4  avg rating: 5    |5.0      |
|ASIN: 0439240751|0439240751|  title: Southern By the Grace of God: Lynyrd Skynyrd Tribute Tour, Vol. 1                 |Southern By the Grace of God: Lynyrd Skynyrd Tribute Tour, Vol. 1                 |  group: Music|Music   |  reviews: total: 6  downloaded: 6  avg rating: 4    |4.0      |
|ASIN: B000002O8D|B000002O8D|  title: Burnt Toast on Davenport Street                                                   |Burnt Toast on Davenport Street                                                   |  group: Book |Book    |  reviews: total: 5  downloaded: 5  avg rating: 4.5  |4.5      |
|ASIN: 0312199406|0312199406|  title: Renovations: A Father and Son Rebuild a House and Rediscover Each Other           |Renovations: A Father and Son Rebuild a House and Rediscover Each Other           |  group: Book |Book    |  reviews: total: 8  downloaded: 8  avg rating: 5    |5.0      |
+----------------+----------+-------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+--------------+--------+-----------------------------------------------------+---------+
only showing top 20 rows

In [51]:
print(final_data.columns)

['value', 'ProductID', 'value', 'Title', 'value', 'Category', 'value', 'AvgRating']

In [53]:
# Print the column names in the DataFrame
print(final_data.columns)

['value', 'ProductID', 'value', 'Title', 'value', 'Category', 'value', 'AvgRating']

In [55]:
# Use the uploaded file in Spark
df = spark.read.csv("1000_rows_in_csv.csv", header=True, inferSchema=True)
df.show(5)

+----------------+----------+--------------------+--------------------+--------------+--------+--------------------+---------+
|   value_product| ProductID|         value_title|               Title|value_category|Category|        value_rating|AvgRating|
+----------------+----------+--------------------+--------------------+--------------+--------+--------------------+---------+
|ASIN: 0771044445|0771044445|title: Patterns o...|Patterns of Preac...|   group: Book|    Book|reviews: total: 2...|      5.0|
|ASIN: 0827229534|0827229534|title: Candlemas:...|Candlemas: Feast ...|   group: Book|    Book|reviews: total: 1...|      4.5|
|ASIN: 1577943082|1577943082|title: How the Ot...|How the Other Hal...|   group: Book|    Book|reviews: total: 1...|      4.0|
|ASIN: 0486220125|0486220125|        title: Batik|               Batik|  group: Music|   Music|reviews: total: 3...|      4.5|
|ASIN: B00000AU3R|B00000AU3R|title: Losing Mat...| Losing Matt Shepard|   group: Book|    Book|reviews: total: 1...|      4.5|
+----------------+----------+--------------------+--------------------+--------------+--------+--------------------+---------+
only showing top 5 rows

In [56]:
df = pd.read_csv(next(iter(uploaded)), on_bad_lines='skip')
df.head()

,value_product,ProductID,value_title,Title,value_category,Category,value_rating,AvgRating
0,ASIN: 0771044445,0771044445,title: Patterns of Preaching: A Sermon Sampler,Patterns of Preaching: A Sermon Sampler,group: Book,Book,reviews: total: 2 downloaded: 2 avg rating: 5,5.0
1,ASIN: 0827229534,0827229534,title: Candlemas: Feast of Flames,Candlemas: Feast of Flames,group: Book,Book,reviews: total: 12 downloaded: 12 avg rating...,4.5
2,ASIN: 1577943082,1577943082,title: How the Other Half Lives: Studies Among...,How the Other Half Lives: Studies Among the Te...,group: Book,Book,reviews: total: 17 downloaded: 17 avg rating: 4,4.0
3,ASIN: 0486220125,0486220125,title: Batik,Batik,group: Music,Music,reviews: total: 3 downloaded: 3 avg rating: 4.5,4.5
4,ASIN: B00000AU3R,B00000AU3R,title: Losing Matt Shepard,Losing Matt Shepard,group: Book,Book,reviews: total: 15 downloaded: 15 avg rating...,4.5

In [57]:
with open(next(iter(uploaded)), 'r') as f:
    lines = f.readlines()
    print(lines[270:300])  # Print lines around line 287 to inspect them

['ASIN: 6304972857,6304972857,title: A-1 Photography Practice Set for Accounting,A-1 Photography Practice Set for Accounting,group: Book,Book,reviews: total: 0  downloaded: 0  avg rating: 0,0\n', 'ASIN: 0895299860,0895299860,title: Partnering Intelligence: Creating Value for Your Business by Building Smart Alliances,Partnering Intelligence: Creating Value for Your Business by Building Smart Alliances,group: Book,Book,reviews: total: 6  downloaded: 6  avg rating: 5,5\n', 'ASIN: 0028639197,0028639197,title: Musicology and Difference: Gender and Sexuality in Music Scholarship,Musicology and Difference: Gender and Sexuality in Music Scholarship,group: Book,Book,reviews: total: 0  downloaded: 0  avg rating: 0,0\n', 'ASIN: 0452280362,0452280362,title: Inventing Catholic Tradition,Inventing Catholic Tradition,group: Book,Book,reviews: total: 0  downloaded: 0  avg rating: 0,0\n', 'ASIN: 1887734317,1887734317,title: Balance of the Force,Balance of the Force,group: Music,Music,reviews: total: 6  downloaded: 6  avg rating: 5,5\n', 'ASIN: 0966854713,0966854713,title: Anne-Sophie Mutter - A Life with Beethoven,Anne-Sophie Mutter - A Life with Beethoven,group: DVD,DVD,reviews: total: 4  downloaded: 4  avg rating: 5,5\n', 'ASIN: B00000K2C1,B00000K2C1,title: Sacred Steel Live!,Sacred Steel Live!,group: Music,Music,reviews: total: 7  downloaded: 7  avg rating: 5,5\n', 'ASIN: B000050X32,B000050X32,title: El corazón de piedra verde,El corazón de piedra verde,group: Book,Book,reviews: total: 0  downloaded: 0  avg rating: 0,0\n', 'ASIN: B00006GA32,B00006GA32,title: Training Youth for Dynamic Leadership,Training Youth for Dynamic Leadership,group: Book,Book,reviews: total: 0  downloaded: 0  avg rating: 0,0\n', 'ASIN: B00000K2C5,B00000K2C5,"title: Attack of the Amazons (The Seven Sleepers , No 8)","Attack of the Amazons (The Seven Sleepers , No 8)",group: Book,Book,reviews: total: 9  downloaded: 9  avg rating: 3.5,3.5\n', 'ASIN: 9500715899,9500715899,title: Chet Baker Quartet Featuring Russ Freeman,Chet Baker Quartet Featuring Russ Freeman,group: Music,Music,reviews: total: 4  downloaded: 4  avg rating: 5,5\n', 'ASIN: 0802436919,0802436919,title: Bring It On!,Bring It On!,group: Music,Music,reviews: total: 0  downloaded: 0  avg rating: 0,0\n', 'ASIN: B00005KB59,B00005KB59,title: Mathematics Dictionary and Handbook,Mathematics Dictionary and Handbook,group: Book,Book,reviews: total: 1  downloaded: 1  avg rating: 5,5\n', 'ASIN: 0415141176,0415141176,"title: Union Bust (Destroyer, 7)","Union Bust (Destroyer, 7)",group: Book,Book,reviews: total: 0  downloaded: 0  avg rating: 0,0\n', 'ASIN: 1561502391,1561502391,title: Synopsis of Cardiac Physical Diagnosis,Synopsis of Cardiac Physical Diagnosis,group: Book,Book,reviews: total: 0  downloaded: 0  avg rating: 0,0\n', 'ASIN: 0830714049,0830714049,"title: Greek Mathematical Works:  Thales to Euclid (Loeb Classical Library, No. 335)","Greek Mathematical Works:  Thales to Euclid (Loeb Classical Library, No. 335)",group: Book,Book,reviews: total: 0  downloaded: 0  avg rating: 0,0\n', 'ASIN: 0674993691,0674993691,"title: \\"Digo  yo como mujer\\", Catalina D`Erzell (Feminista de México)","\\"Digo  yo como mujer\\", Catalina D`Erzell (Feminista de México)",group: Book,Book,reviews: total: 0  downloaded: 0  avg rating: 0,0\n', 'ASIN: B000002VTR,B000002VTR,title: Classical Art: From Greece to Rome (Oxford History of Art),Classical Art: From Greece to Rome (Oxford History of Art),group: Book,Book,reviews: total: 1  downloaded: 1  avg rating: 5,5\n', 'ASIN: 0226519996,0226519996,title: Descendants of Noah: Stories of Armenian Apostolic Faith and Heritage,Descendants of Noah: Stories of Armenian Apostolic Faith and Heritage,group: Book,Book,reviews: total: 0  downloaded: 0  avg rating: 0,0\n', "ASIN: 186100818X,186100818X,title: Forgetting Whose We Are: Alzheimer's Disease and the Love of God,Forgetting Whose We Are: Alzheimer's Disease and the Love of God,group: Book,Book,reviews: total: 0  downloaded: 0  avg rating: 0,0\n", 'ASIN: B00005KB5Q,B00005KB5Q,title: And His Orchestra,And His Orchestra,group: Music,Music,reviews: total: 0  downloaded: 0  avg rating: 0,0\n', 'ASIN: B0000648L1,B0000648L1,title: The SECRET OF THE BULLS,The SECRET OF THE BULLS,group: Book,Book,reviews: total: 5  downloaded: 5  avg rating: 5,5\n', 'ASIN: 048641793X,048641793X,title: Teaching U.S. Puerto Rican History (Teaching Diversity),Teaching U.S. Puerto Rican History (Teaching Diversity),group: Book,Book,reviews: total: 0  downloaded: 0  avg rating: 0,0\n', 'ASIN: 0970007914,0970007914,title: Vince Lombardi Video Football Card,Vince Lombardi Video Football Card,group: Video,Video,reviews: total: 0  downloaded: 0  avg rating: 0,0\n', 'ASIN: 0684831376,0684831376,title: Baudelaire,Baudelaire,group: Book,Book,reviews: total: 3  downloaded: 3  avg rating: 4,4\n', 'ASIN: 0789428660,0789428660,title: NIV Compact Dictionary of the Bible,NIV Compact Dictionary of the Bible,group: Book,Book,reviews: total: 2  downloaded: 2  avg rating: 3.5,3.5\n', 'ASIN: 1591821924,1591821924,title: Retrograss,Retrograss,group: Music,Music,reviews: total: 7  downloaded: 7  avg rating: 4.5,4.5\n', 'ASIN: 6301701720,6301701720,title: Simply Grand,Simply Grand,group: Music,Music,reviews: total: 4  downloaded: 4  avg rating: 5,5\n', 'ASIN: 0811201899,0811201899,title: I Wish I Had a Red Dress,I Wish I Had a Red Dress,group: Book,Book,reviews: total: 78  downloaded: 5  avg rating: 4,4\n', 'ASIN: 0310228735,0310228735,"title: Selections from The Beatles Anthology, Volume 1 (Selections from the Beatles Anthology)","Selections from The Beatles Anthology, Volume 1 (Selections from the Beatles Anthology)",group: Book,Book,reviews: total: 1  downloaded: 1  avg rating: 3,3\n']

In [58]:
import pandas as pd

# Manually creating the data from the list you shared
data = [
    'ASIN: 6304972857,6304972857,title: A-1 Photography Practice Set for Accounting,A-1 Photography Practice Set for Accounting,group: Book,Book,reviews: total: 0  downloaded: 0  avg rating: 0,0\n',
    'ASIN: 0895299860,0895299860,title: Partnering Intelligence: Creating Value for Your Business by Building Smart Alliances,Partnering Intelligence: Creating Value for Your Business by Building Smart Alliances,group: Book,Book,reviews: total: 6  downloaded: 6  avg rating: 5,5\n',
    # ... (your full data here)
]

# Convert the list into a DataFrame
# First, join the data into a single string, then split by newlines
data_str = ''.join(data)

# Convert into a pandas DataFrame
from io import StringIO
df = pd.read_csv(StringIO(data_str), header=None)

# Display the dataframe
df.head()

,0,1,2,3,4,5,6,7
0,ASIN: 6304972857,6304972857,title: A-1 Photography Practice Set for Accoun...,A-1 Photography Practice Set for Accounting,group: Book,Book,reviews: total: 0 downloaded: 0 avg rating: 0,0
1,ASIN: 0895299860,895299860,title: Partnering Intelligence: Creating Value...,Partnering Intelligence: Creating Value for Yo...,group: Book,Book,reviews: total: 6 downloaded: 6 avg rating: 5,5

In [59]:
import pandas as pd

# Sample data from your earlier output
data = [
    "ASIN: 6304972857,6304972857,title: A-1 Photography Practice Set for Accounting,A-1 Photography Practice Set for Accounting,group: Book,Book,reviews: total: 0 downloaded: 0 avg rating: 0,0",
    "ASIN: 0895299860,0895299860,title: Partnering Intelligence: Creating Value for Your Business by Building Smart Alliances,Partnering Intelligence: Creating Value for Your Business by Building Smart Alliances,group: Book,Book,reviews: total: 6 downloaded: 6 avg rating: 5,5",
    # Add the rest of your data here...
]

# Step 2: Split the data into columns
cleaned_data = []

for row in data:
    parts = row.split(',')

    # Extracting values from the parts and cleaning them
    asin = parts[0].split(":")[1].strip()
    title = parts[2].split(":")[1].strip()
    group = parts[4].split(":")[1].strip()
    reviews = parts[6].split(":")[1].strip()

    cleaned_data.append([asin, title, group, reviews])

# Step 3: Convert cleaned data into DataFrame
df_cleaned = pd.DataFrame(cleaned_data, columns=['ASIN', 'Title', 'Group', 'Reviews'])

# Step 4: Display the cleaned DataFrame
df_cleaned.head()

         ASIN                                        Title Group Reviews
0  6304972857  A-1 Photography Practice Set for Accounting  Book   total
1  0895299860                      Partnering Intelligence  Book   total

In [60]:
import pandas as pd
import re

# Assuming the raw data is stored in the `data` variable
# Example of raw data as list of strings
data = ['ASIN: 6304972857,6304972857,title: A-1 Photography Practice Set for Accounting,A-1 Photography Practice Set for Accounting,group: Book,Book,reviews: total: 0 downloaded: 0 avg rating: 0,0\n',
        'ASIN: 0895299860,0895299860,title: Partnering Intelligence: Creating Value for Your Business by Building Smart Alliances,Partnering Intelligence: Creating Value for Your Business by Building Smart Alliances,group: Book,Book,reviews: total: 6 downloaded: 6 avg rating: 5,5\n',
        'ASIN: 0028639197,0028639197,title: Musicology and Difference: Gender and Sexuality in Music Scholarship,Musicology and Difference: Gender and Sexuality in Music Scholarship,group: Book,Book,reviews: total: 0 downloaded: 0 avg rating: 0,0\n']

# Parse the data and clean it
parsed_data = []

for line in data:
    try:
        # Splitting the string by commas
        parts = line.strip().split(',')

        # Ensure that each part is properly indexed
        if len(parts) >= 8:
            asin = parts[0].split(":")[1].strip()
            title = parts[2].split(":")[1].strip()
            group = parts[4].split(":")[1].strip()

            # Extract reviews info
            reviews = parts[6].split(" ")
            total_reviews = reviews[1]
            downloaded = reviews[3]
            avg_rating = reviews[5]

            # Append the cleaned data
            parsed_data.append([asin, title, group, total_reviews, downloaded, avg_rating])
    except Exception as e:
        print(f"Error processing line: {line}\n{str(e)}")

# Create a DataFrame with the parsed data
df = pd.DataFrame(parsed_data, columns=['ASIN', 'Title', 'Group', 'Total Reviews', 'Downloaded', 'Avg Rating'])

# Show the resulting DataFrame
df.head()

,ASIN,Title,Group,Total Reviews,Downloaded,Avg Rating
0,6304972857,A-1 Photography Practice Set for Accounting,Book,total:,downloaded:,avg
1,0895299860,Partnering Intelligence,Book,total:,downloaded:,avg
2,0028639197,Musicology and Difference,Book,total:,downloaded:,avg

In [61]:
import pandas as pd
import re

# Assuming the raw data is stored in the `data` variable
data = ['ASIN: 6304972857,6304972857,title: A-1 Photography Practice Set for Accounting,A-1 Photography Practice Set for Accounting,group: Book,Book,reviews: total: 0 downloaded: 0 avg rating: 0,0\n',
        'ASIN: 0895299860,0895299860,title: Partnering Intelligence: Creating Value for Your Business by Building Smart Alliances,Partnering Intelligence: Creating Value for Your Business by Building Smart Alliances,group: Book,Book,reviews: total: 6 downloaded: 6 avg rating: 5,5\n',
        'ASIN: 0028639197,0028639197,title: Musicology and Difference: Gender and Sexuality in Music Scholarship,Musicology and Difference: Gender and Sexuality in Music Scholarship,group: Book,Book,reviews: total: 0 downloaded: 0 avg rating: 0,0\n']

# Parse the data and clean it
parsed_data = []

for line in data:
    try:
        # Splitting the string by commas
        parts = line.strip().split(',')

        # Ensure that each part is properly indexed
        if len(parts) >= 8:
            asin = parts[0].split(":")[1].strip()
            title = parts[2].split(":")[1].strip()
            group = parts[4].split(":")[1].strip()

            # Extract reviews info
            reviews_str = parts[6]
            total_reviews = re.search(r'total: (\d+)', reviews_str).group(1) if re.search(r'total: (\d+)', reviews_str) else "0"
            downloaded = re.search(r'downloaded: (\d+)', reviews_str).group(1) if re.search(r'downloaded: (\d+)', reviews_str) else "0"
            avg_rating = re.search(r'avg rating: ([\d\.]+)', reviews_str).group(1) if re.search(r'avg rating: ([\d\.]+)', reviews_str) else "0.0"

            # Append the cleaned data
            parsed_data.append([asin, title, group, total_reviews, downloaded, avg_rating])
    except Exception as e:
        print(f"Error processing line: {line}\n{str(e)}")

# Create a DataFrame with the parsed data
df = pd.DataFrame(parsed_data, columns=['ASIN', 'Title', 'Group', 'Total Reviews', 'Downloaded', 'Avg Rating'])

# Show the resulting DataFrame
df.head()

,ASIN,Title,Group,Total Reviews,Downloaded,Avg Rating
0,6304972857,A-1 Photography Practice Set for Accounting,Book,0,0,0
1,0895299860,Partnering Intelligence,Book,6,6,5
2,0028639197,Musicology and Difference,Book,0,0,0

In [63]:
import pandas as pd

# Load the CSV with error handling
try:
    df = pd.read_csv("1000_rows_in_csv.csv",
                     quotechar='"',
                     delimiter=',',
                     on_bad_lines='skip')
    print("CSV loaded successfully.")
except Exception as e:
    print("Error loading CSV:", e)

# Clean the data by removing the unwanted prefixes
df['ProductID'] = df['value_product'].str.split(':').str[1].str.strip()
df['Title'] = df['value_title'].str.split(':').str[1].str.strip()
df['Category'] = df['value_category'].str.split(':').str[1].str.strip()
df['AvgRating'] = df['value_rating'].str.split(':').str[2].str.strip()

# Drop the unnecessary columns
df.drop(columns=['value_product', 'value_title', 'value_category', 'value_rating'], inplace=True)

# Check the first few rows of the cleaned data
print(df.head())

CSV loaded successfully.
    ProductID                     Title Category       AvgRating
0  0771044445     Patterns of Preaching     Book   2  downloaded
1  0827229534                 Candlemas     Book  12  downloaded
2  1577943082  How the Other Half Lives     Book  17  downloaded
3  0486220125                     Batik    Music   3  downloaded
4  B00000AU3R       Losing Matt Shepard     Book  15  downloaded

In [64]:
import pandas as pd

# Load the CSV with error handling
try:
    df = pd.read_csv("1000_rows_in_csv.csv",
                     quotechar='"',
                     delimiter=',',
                     on_bad_lines='skip')
    print("CSV loaded successfully.")
except Exception as e:
    print("Error loading CSV:", e)

# Check the total number of rows before cleaning
print(f"Total rows in CSV before cleaning: {len(df)}")

# Clean the data by removing the unwanted prefixes
df['ProductID'] = df['value_product'].str.split(':').str[1].str.strip()
df['Title'] = df['value_title'].str.split(':').str[1].str.strip()
df['Category'] = df['value_category'].str.split(':').str[1].str.strip()
df['AvgRating'] = df['value_rating'].str.split(':').str[2].str.strip()

# Drop the unnecessary columns
df.drop(columns=['value_product', 'value_title', 'value_category', 'value_rating'], inplace=True)

# Check the total number of rows after cleaning
print(f"Total rows after cleaning: {len(df)}")

# Check the first few rows of the cleaned data
print(df.head())

CSV loaded successfully.
Total rows in CSV before cleaning: 273426
Total rows after cleaning: 273426
    ProductID                     Title Category       AvgRating
0  0771044445     Patterns of Preaching     Book   2  downloaded
1  0827229534                 Candlemas     Book  12  downloaded
2  1577943082  How the Other Half Lives     Book  17  downloaded
3  0486220125                     Batik    Music   3  downloaded
4  B00000AU3R       Losing Matt Shepard     Book  15  downloaded

In [ ]:
import pandas as pd

# Load the CSV with error handling
try:
    df = pd.read_csv("1000_rows_in_csv.csv",
                     quotechar='"',
                     delimiter=',',
                     on_bad_lines='skip')
    print("CSV loaded successfully.")
except Exception as e:
    print("Error loading CSV:", e)

# Check the total number of rows before cleaning
print(f"Total rows in CSV before cleaning: {len(df)}")

# Clean the data by removing the unwanted prefixes
df['ProductID'] = df['value_product'].str.split(':').str[1].str.strip()
df['Title'] = df['value_title'].str.split(':').str[1].str.strip()
df['Category'] = df['value_category'].str.split(':').str[1].str.strip()

# Clean the AvgRating column to remove 'downloaded' and keep only the number
df['AvgRating'] = df['value_rating'].str.split(':').str[2].str.extract('(\d+)', expand=False)

# Drop the unnecessary columns
df.drop(columns=['value_product', 'value_title', 'value_category', 'value_rating'], inplace=True)

# Check the total number of rows after cleaning
print(f"Total rows after cleaning: {len(df)}")

# Check the first few rows of the cleaned data
print(df.head())

CSV loaded successfully.
Total rows in CSV before cleaning: 273426
Total rows after cleaning: 273426
    ProductID                     Title Category AvgRating
0  0771044445     Patterns of Preaching     Book         2
1  0827229534                 Candlemas     Book        12
2  1577943082  How the Other Half Lives     Book        17
3  0486220125                     Batik    Music         3
4  B00000AU3R       Losing Matt Shepard     Book        15

In [ ]:
import pandas as pd

# Load the CSV with error handling
try:
    df = pd.read_csv("1000_rows_in_csv.csv",
                     quotechar='"',
                     delimiter=',',
                     on_bad_lines='skip')
    print("CSV loaded successfully.")
except Exception as e:
    print("Error loading CSV:", e)

# Check the total number of rows before cleaning
print(f"Total rows in CSV before cleaning: {len(df)}")

# Clean the data by removing the unwanted prefixes
df['ProductID'] = df['value_product'].str.split(':').str[1].str.strip()
df['Title'] = df['value_title'].str.split(':').str[1].str.strip()
df['Category'] = df['value_category'].str.split(':').str[1].str.strip()

# Clean the AvgRating column to remove 'downloaded' and keep only the number
df['AvgRating'] = df['value_rating'].str.split(':').str[2].str.extract('(\d+)', expand=False)

# Drop the unnecessary columns
df.drop(columns=['value_product', 'value_title', 'value_category', 'value_rating'], inplace=True)

# Check the total number of rows after cleaning
print(f"Total rows after cleaning: {len(df)}")

# Check the first few rows of the cleaned data
print(df.head())

CSV loaded successfully.
Total rows in CSV before cleaning: 273426
Total rows after cleaning: 273426
    ProductID                     Title Category AvgRating
0  0771044445     Patterns of Preaching     Book         2
1  0827229534                 Candlemas     Book        12
2  1577943082  How the Other Half Lives     Book        17
3  0486220125                     Batik    Music         3
4  B00000AU3R       Losing Matt Shepard     Book        15

In [171]:
import pandas as pd

# Load the CSV with error handling
try:
    df = pd.read_csv("1000_rows_in_csv.csv",
                     quotechar='"',
                     delimiter=',',
                     on_bad_lines='skip')
    print("CSV loaded successfully.")
except Exception as e:
    print("Error loading CSV:", e)

# Check the columns to see if 'value_rating' is available
print("Columns in DataFrame:", df.columns)

# Extract the 'AvgRating' before dropping the 'value_rating' column
if 'value_rating' in df.columns:
    df['AvgRating'] = df['value_rating'].str.extract(r'total[:\s]*([\d]+)[\s]*downloaded')
    df['AvgRating'] = pd.to_numeric(df['AvgRating'], errors='coerce')
else:
    print("Column 'value_rating' is missing!")

# Clean the data by removing the unwanted prefixes from the other columns
df['ProductID'] = df['value_product'].str.split(':').str[1].str.strip()
df['Title'] = df['value_title'].str.split(':').str[1].str.strip()
df['Category'] = df['value_category'].str.split(':').str[1].str.strip()

# Drop the unnecessary columns after extraction
df.drop(columns=['value_product', 'value_title', 'value_category', 'value_rating'], inplace=True)

# Check the total number of rows after cleaning
print(f"Total rows after cleaning: {len(df)}")

# Display the first 50 rows of the cleaned data
print(df.head(50))

CSV loaded successfully.
Columns in DataFrame: Index(['value_product', 'ProductID', 'value_title', 'Title', 'value_category',
       'Category', 'value_rating', 'AvgRating'],
      dtype='object')
Total rows after cleaning: 273426
     ProductID                                                      Title  \
0   0771044445                                      Patterns of Preaching
1   0827229534                                                  Candlemas
2   1577943082                                   How the Other Half Lives
3   0486220125                                                      Batik
4   B00000AU3R                                        Losing Matt Shepard
5   1859677800                                     The Edward Said Reader
6   0375709363                                        Resetting the Clock
7   0849311012                                                Sol to Soul
8   078510870X                                        Computed Tomography
9   B00005NTSV                                               Strange Fire
10  0939165252                                             Chicken Little
11  1590930509                   The Columbia Anthology of Gay Literature
12  0231096704                       God Knows Marriage Isn't Always Easy
13  1893732290                     Advanced Pediatric Clinical Assessment
14  0781718791                      Solving Statics Problems with MathCAD
15  0895872218                               Staff Meals from Chanterelle
16  0761116982                             Double Jeopardy (T*Witches, 6)
17  0439240751                               Southern By the Grace of God
18  B000002O8D                            Burnt Toast on Davenport Street
19  0312199406                                                Renovations
20  0130132543                                                     Pixote
21  0486268780                               The NBA's 100 Greatest Plays
22  B000056PNE                       Beginning ASP.NET Databases using C#
23  0439420717                                           Murder She Wrote
24  B00004W1WK                                            Out on the Edge
25  0687054532  Secrets of Gypsy Love Magick (Llewellyn's New Age Series)
26  0875420532                                     Baby Boomer Retirement
27  0613100093                             Goldilocks and the Three Bears
28  1550416243                               Investigating Computer Crime
29  0398068917                                     Raptors of the Rockies
30  087842461X                                  None But the Lonely Heart
31  0966723821                                  A Charlie Brown Christmas
32  0273651870                                             Blood and Guts
33  1571515429                   Experiencing and the Creation of Meaning
34  0810114275                                         Negotiated Empires
35  B0000060T5                                           Power of Flowers
36  157281196X                              The Perfect Plan (7th Heaven)
37  0312982178                                         The Ebony Cookbook
38  0811726371                                            In Quest of God
39  B000063W82                                  Amamantar Sencillo y Puro
40  0912500476                                  Junie B. Jones Collection
41  0415157528                            Normal and Abnormal Development
42  039802278X                                    Desde Que Samba E Samba
43  B00005ARCQ                                       The Eagle Has Landed
44  039572774X                             The Heavy Flak Guns, 1933-1945
45  0887402631                            Becoming a Contagious Christian
46  0310485002                                          Year of the Tiger
47  B0000646IJ                       An Employee's Guide to Stock Options
48  0787958743                                        Separation Of Power
49  0151803870                                             Owning Culture

   Category  AvgRating
0      Book        2.0
1      Book       12.0
2      Book       17.0
3     Music        3.0
4      Book       15.0
5      Book        6.0
6      Book        1.0
7     Music       15.0
8      Book        1.0
9      Book        3.0
10     Book        1.0
11     Book        2.0
12     Book        0.0
13     Book        0.0
14     Book        0.0
15     Book       11.0
16     Book        4.0
17    Music        6.0
18     Book        5.0
19     Book        8.0
20      DVD       24.0
21      DVD       13.0
22     Book        4.0
23    Music        0.0
24     Book        7.0
25     Book        6.0
26     Book        1.0
27     Book        1.0
28     Book        1.0
29     Book        0.0
30    Video        5.0
31     Book        6.0
32     Book        4.0
33     Book        1.0
34     Book        0.0
35     Book        3.0
36     Book        2.0
37     Book        3.0
38     Book        1.0
39     Book        0.0
40     Book        4.0
41     Book        0.0
42    Music        0.0
43     Book       46.0
44     Book        0.0
45     Book       21.0
46     Book        5.0
47     Book        0.0
48     Book       76.0
49     Book        0.0

In [172]:
# Load the CSV with error handling
try:
    df = pd.read_csv("1000_rows_in_csv.csv", quotechar='"', delimiter=',', on_bad_lines='skip')
    print("CSV loaded successfully.")
except Exception as e:
    print("Error loading CSV:", e)

# Check the columns of the DataFrame to see if 'value_rating' exists
print("Columns in DataFrame:", df.columns)

CSV loaded successfully.
Columns in DataFrame: Index(['value_product', 'ProductID', 'value_title', 'Title', 'value_category',
       'Category', 'value_rating', 'AvgRating'],
      dtype='object')

In [173]:
print(df.head(10))  # Print the first 10 rows to check the data

      value_product   ProductID  \
0  ASIN: 0771044445  0771044445
1  ASIN: 0827229534  0827229534
2  ASIN: 1577943082  1577943082
3  ASIN: 0486220125  0486220125
4  ASIN: B00000AU3R  B00000AU3R
5  ASIN: 1859677800  1859677800
6  ASIN: 0375709363  0375709363
7  ASIN: 0849311012  0849311012
8  ASIN: 078510870X  078510870X
9  ASIN: B00005NTSV  B00005NTSV

                                                                                 value_title  \
0                                             title: Patterns of Preaching: A Sermon Sampler
1                                                          title: Candlemas: Feast of Flames
2                   title: How the Other Half Lives: Studies Among the Tenements of New York
3                                                                               title: Batik
4                                                                 title: Losing Matt Shepard
5                                                              title: The Edward Said Reader
6         title: Resetting the Clock : Five Anti-Aging Hormones That Improve and Extend Life
7                                                                         title: Sol to Soul
8  title: Computed Tomography : Fundamentals, System Technology, Image Quality, Applications
9                                                               title: Strange Fire: A Novel

                                                                                Title  \
0                                             Patterns of Preaching: A Sermon Sampler
1                                                          Candlemas: Feast of Flames
2                   How the Other Half Lives: Studies Among the Tenements of New York
3                                                                               Batik
4                                                                 Losing Matt Shepard
5                                                              The Edward Said Reader
6         Resetting the Clock : Five Anti-Aging Hormones That Improve and Extend Life
7                                                                         Sol to Soul
8  Computed Tomography : Fundamentals, System Technology, Image Quality, Applications
9                                                               Strange Fire: A Novel

  value_category Category  \
0    group: Book     Book
1    group: Book     Book
2    group: Book     Book
3   group: Music    Music
4    group: Book     Book
5    group: Book     Book
6    group: Book     Book
7   group: Music    Music
8    group: Book     Book
9    group: Book     Book

                                          value_rating  AvgRating
0      reviews: total: 2  downloaded: 2  avg rating: 5        5.0
1  reviews: total: 12  downloaded: 12  avg rating: 4.5        4.5
2    reviews: total: 17  downloaded: 17  avg rating: 4        4.0
3    reviews: total: 3  downloaded: 3  avg rating: 4.5        4.5
4  reviews: total: 15  downloaded: 15  avg rating: 4.5        4.5
5      reviews: total: 6  downloaded: 6  avg rating: 4        4.0
6      reviews: total: 1  downloaded: 1  avg rating: 5        5.0
7    reviews: total: 15  downloaded: 15  avg rating: 5        5.0
8      reviews: total: 1  downloaded: 1  avg rating: 5        5.0
9      reviews: total: 3  downloaded: 3  avg rating: 3        3.0

In [174]:
import pandas as pd

# Load the CSV with error handling
try:
    df = pd.read_csv("1000_rows_in_csv.csv", quotechar='"', delimiter=',', on_bad_lines='skip')
    print("CSV loaded successfully.")
except Exception as e:
    print("Error loading CSV:", e)

# Check the columns to verify 'value_rating' exists
print("Columns in DataFrame:", df.columns)

# Extract 'AvgRating' from 'value_rating' column using regex
df['AvgRating'] = df['value_rating'].str.extract(r'avg rating:\s*(\d+)', expand=False)

# Convert 'AvgRating' to numeric values
df['AvgRating'] = pd.to_numeric(df['AvgRating'], errors='coerce')

# Clean other columns (if needed)
df['ProductID'] = df['value_product'].str.split(':').str[1].str.strip()
df['Title'] = df['value_title'].str.split(':').str[1].str.strip()
df['Category'] = df['value_category'].str.split(':').str[1].str.strip()

# Drop unnecessary columns
df.drop(columns=['value_product', 'value_title', 'value_category', 'value_rating'], inplace=True)

# Check first few rows of the cleaned DataFrame
print(df.head(50))  # Adjust the number if needed

CSV loaded successfully.
Columns in DataFrame: Index(['value_product', 'ProductID', 'value_title', 'Title', 'value_category',
       'Category', 'value_rating', 'AvgRating'],
      dtype='object')
     ProductID                                                      Title  \
0   0771044445                                      Patterns of Preaching
1   0827229534                                                  Candlemas
2   1577943082                                   How the Other Half Lives
3   0486220125                                                      Batik
4   B00000AU3R                                        Losing Matt Shepard
5   1859677800                                     The Edward Said Reader
6   0375709363                                        Resetting the Clock
7   0849311012                                                Sol to Soul
8   078510870X                                        Computed Tomography
9   B00005NTSV                                               Strange Fire
10  0939165252                                             Chicken Little
11  1590930509                   The Columbia Anthology of Gay Literature
12  0231096704                       God Knows Marriage Isn't Always Easy
13  1893732290                     Advanced Pediatric Clinical Assessment
14  0781718791                      Solving Statics Problems with MathCAD
15  0895872218                               Staff Meals from Chanterelle
16  0761116982                             Double Jeopardy (T*Witches, 6)
17  0439240751                               Southern By the Grace of God
18  B000002O8D                            Burnt Toast on Davenport Street
19  0312199406                                                Renovations
20  0130132543                                                     Pixote
21  0486268780                               The NBA's 100 Greatest Plays
22  B000056PNE                       Beginning ASP.NET Databases using C#
23  0439420717                                           Murder She Wrote
24  B00004W1WK                                            Out on the Edge
25  0687054532  Secrets of Gypsy Love Magick (Llewellyn's New Age Series)
26  0875420532                                     Baby Boomer Retirement
27  0613100093                             Goldilocks and the Three Bears
28  1550416243                               Investigating Computer Crime
29  0398068917                                     Raptors of the Rockies
30  087842461X                                  None But the Lonely Heart
31  0966723821                                  A Charlie Brown Christmas
32  0273651870                                             Blood and Guts
33  1571515429                   Experiencing and the Creation of Meaning
34  0810114275                                         Negotiated Empires
35  B0000060T5                                           Power of Flowers
36  157281196X                              The Perfect Plan (7th Heaven)
37  0312982178                                         The Ebony Cookbook
38  0811726371                                            In Quest of God
39  B000063W82                                  Amamantar Sencillo y Puro
40  0912500476                                  Junie B. Jones Collection
41  0415157528                            Normal and Abnormal Development
42  039802278X                                    Desde Que Samba E Samba
43  B00005ARCQ                                       The Eagle Has Landed
44  039572774X                             The Heavy Flak Guns, 1933-1945
45  0887402631                            Becoming a Contagious Christian
46  0310485002                                          Year of the Tiger
47  B0000646IJ                       An Employee's Guide to Stock Options
48  0787958743                                        Separation Of Power
49  0151803870                                             Owning Culture

   Category  AvgRating
0      Book        5.0
1      Book        4.0
2      Book        4.0
3     Music        4.0
4      Book        4.0
5      Book        4.0
6      Book        5.0
7     Music        5.0
8      Book        5.0
9      Book        3.0
10     Book        4.0
11     Book        3.0
12     Book        0.0
13     Book        0.0
14     Book        0.0
15     Book        4.0
16     Book        5.0
17    Music        4.0
18     Book        4.0
19     Book        5.0
20      DVD        4.0
21      DVD        4.0
22     Book        4.0
23    Music        0.0
24     Book        4.0
25     Book        4.0
26     Book        5.0
27     Book        4.0
28     Book        1.0
29     Book        0.0
30    Video        4.0
31     Book        3.0
32     Book        4.0
33     Book        5.0
34     Book        0.0
35     Book        5.0
36     Book        4.0
37     Book        4.0
38     Book        5.0
39     Book        0.0
40     Book        5.0
41     Book        0.0
42    Music        0.0
43     Book        4.0
44     Book        0.0
45     Book        4.0
46     Book        4.0
47     Book        0.0
48     Book        4.0
49     Book        0.0

In [175]:
print(df.columns)

Index(['ProductID', 'Title', 'Category', 'AvgRating'], dtype='object')

In [176]:
print(df.columns.tolist())  # Ensure you see the exact column names

['ProductID', 'Title', 'Category', 'AvgRating']

In [177]:
print(df.head())  # Print the first few rows to understand the data

    ProductID                     Title Category  AvgRating
0  0771044445     Patterns of Preaching     Book        5.0
1  0827229534                 Candlemas     Book        4.0
2  1577943082  How the Other Half Lives     Book        4.0
3  0486220125                     Batik    Music        4.0
4  B00000AU3R       Losing Matt Shepard     Book        4.0

In [178]:
import os
print(os.listdir('/content'))  # List files in the /content directory (default for Colab)

['.config', 'drive', '1000_rows_in_csv.csv', 'sample_data']

In [179]:
df = pd.read_csv('/content/1000_rows_in_csv.csv', on_bad_lines='skip')

# Check the first few rows to confirm it's loaded correctly
print(df.head())

      value_product   ProductID  \
0  ASIN: 0771044445  0771044445
1  ASIN: 0827229534  0827229534
2  ASIN: 1577943082  1577943082
3  ASIN: 0486220125  0486220125
4  ASIN: B00000AU3R  B00000AU3R

                                                                value_title  \
0                            title: Patterns of Preaching: A Sermon Sampler
1                                         title: Candlemas: Feast of Flames
2  title: How the Other Half Lives: Studies Among the Tenements of New York
3                                                              title: Batik
4                                                title: Losing Matt Shepard

                                                               Title  \
0                            Patterns of Preaching: A Sermon Sampler
1                                         Candlemas: Feast of Flames
2  How the Other Half Lives: Studies Among the Tenements of New York
3                                                              Batik
4                                                Losing Matt Shepard

  value_category Category  \
0    group: Book     Book
1    group: Book     Book
2    group: Book     Book
3   group: Music    Music
4    group: Book     Book

                                          value_rating  AvgRating
0      reviews: total: 2  downloaded: 2  avg rating: 5        5.0
1  reviews: total: 12  downloaded: 12  avg rating: 4.5        4.5
2    reviews: total: 17  downloaded: 17  avg rating: 4        4.0
3    reviews: total: 3  downloaded: 3  avg rating: 4.5        4.5
4  reviews: total: 15  downloaded: 15  avg rating: 4.5        4.5

In [159]:
def get_best_n_sellers(df, category, n):
    top_sellers = df[df['Category'] == category].sort_values(by='AvgRating', ascending=False).head(n)
    return top_sellers[['ProductID', 'Title', 'AvgRating']]

# Example usage
best_books = get_best_n_sellers(df, 'Book', 10)  # Get the top 10 best books
print(best_books)

         ProductID  \
273405  0972380108
273400  156720273X
273399  0825434645
273396  1564290484
273394  0825434904
273392  0451410505
273388  0312284861
38      0811726371
35      B0000060T5
33      1571515429

                                                                                                                                                               Title  \
273405                             Start Your Own Computer Business: Building a Successful PC Repair and Service Business by Supporting Customers and Managing Money
273400                                                                              Business Strategy Formulation : Theory, Process, and the Intellectual Revolution
273399                                                                                                        George Muller of Bristol: His Life of Prayer and Faith
273396                                                                                                                                  Mergent's Dividend Achievers
273394                                                                                Exploring Acts: An Expository Commentary (The John Phillips Commentary Series)
273392                                                                                                                                              Black Jack Point
273388                                                                                              How to Spot a Bastard by His Star Sign: The Ultimate Horrorscope
38                                                                                                          In Quest of God: The Saga of an Extraordinary Pilgrimage
35                                                                                                            Power of Flowers: An Archetypal Journey Through Nature
33      Experiencing and the Creation of Meaning: A Philosophical and Psychological Approach to the Subjective (Studies in Phenomenology and Existential Philosophy)

        AvgRating
273405        5.0
273400        5.0
273399        5.0
273396        5.0
273394        5.0
273392        5.0
273388        5.0
38            5.0
35            5.0
33            5.0

In [160]:
print(df.head())  # Display the first 5 rows
print(df.tail())  # Display the last 5 rows
print(df.info())  # Get info about the dataset (columns, types, missing values)

      value_product   ProductID  \
0  ASIN: 0771044445  0771044445
1  ASIN: 0827229534  0827229534
2  ASIN: 1577943082  1577943082
3  ASIN: 0486220125  0486220125
4  ASIN: B00000AU3R  B00000AU3R

                                                                value_title  \
0                            title: Patterns of Preaching: A Sermon Sampler
1                                         title: Candlemas: Feast of Flames
2  title: How the Other Half Lives: Studies Among the Tenements of New York
3                                                              title: Batik
4                                                title: Losing Matt Shepard

                                                               Title  \
0                            Patterns of Preaching: A Sermon Sampler
1                                         Candlemas: Feast of Flames
2  How the Other Half Lives: Studies Among the Tenements of New York
3                                                              Batik
4                                                Losing Matt Shepard

  value_category Category  \
0    group: Book     Book
1    group: Book     Book
2    group: Book     Book
3   group: Music    Music
4    group: Book     Book

                                          value_rating  AvgRating
0      reviews: total: 2  downloaded: 2  avg rating: 5        5.0
1  reviews: total: 12  downloaded: 12  avg rating: 4.5        4.5
2    reviews: total: 17  downloaded: 17  avg rating: 4        4.0
3    reviews: total: 3  downloaded: 3  avg rating: 4.5        4.5
4  reviews: total: 15  downloaded: 15  avg rating: 4.5        4.5
           value_product   ProductID  \
273421  ASIN: 9627762644  9627762644
273422  ASIN: 0970020503  0970020503
273423  ASIN: B000065AHM  B000065AHM
273424  ASIN: B000059TOC  B000059TOC
273425  ASIN: B00006JBIX  B00006JBIX

                                            value_title  \
273421  title: Starting a Hedge Fund : A US Perspective
273422    title: Facts Every Injured Worker Should Know
273423                                 title: Lucky Man
273424                               title: The Drifter
273425                     title: The House Of Morecock

                                           Title value_category Category  \
273421  Starting a Hedge Fund : A US Perspective    group: Book     Book
273422    Facts Every Injured Worker Should Know    group: Book     Book
273423                                 Lucky Man   group: Music    Music
273424                               The Drifter     group: DVD      DVD
273425                     The House Of Morecock     group: DVD      DVD

                                             value_rating  AvgRating
273421    reviews: total: 1  downloaded: 1  avg rating: 4        4.0
273422  reviews: total: 3  downloaded: 3  avg rating: 2.5        2.5
273423  reviews: total: 5  downloaded: 5  avg rating: 4.5        4.5
273424    reviews: total: 2  downloaded: 2  avg rating: 5        5.0
273425    reviews: total: 1  downloaded: 1  avg rating: 5        5.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 273426 entries, 0 to 273425
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   value_product   273426 non-null  object
 1   ProductID       273426 non-null  object
 2   value_title     270464 non-null  object
 3   Title           270464 non-null  object
 4   value_category  270464 non-null  object
 5   Category        270464 non-null  object
 6   value_rating    270464 non-null  object
 7   AvgRating       270456 non-null  float64
dtypes: float64(1), object(7)
memory usage: 16.7+ MB
None

In [161]:
df.dropna(subset=['Title', 'Category', 'AvgRating'], inplace=True)  # Drop rows with missing essential info

In [162]:
print(df.head())

      value_product   ProductID  \
0  ASIN: 0771044445  0771044445
1  ASIN: 0827229534  0827229534
2  ASIN: 1577943082  1577943082
3  ASIN: 0486220125  0486220125
4  ASIN: B00000AU3R  B00000AU3R

                                                                value_title  \
0                            title: Patterns of Preaching: A Sermon Sampler
1                                         title: Candlemas: Feast of Flames
2  title: How the Other Half Lives: Studies Among the Tenements of New York
3                                                              title: Batik
4                                                title: Losing Matt Shepard

                                                               Title  \
0                            Patterns of Preaching: A Sermon Sampler
1                                         Candlemas: Feast of Flames
2  How the Other Half Lives: Studies Among the Tenements of New York
3                                                              Batik
4                                                Losing Matt Shepard

  value_category Category  \
0    group: Book     Book
1    group: Book     Book
2    group: Book     Book
3   group: Music    Music
4    group: Book     Book

                                          value_rating  AvgRating
0      reviews: total: 2  downloaded: 2  avg rating: 5        5.0
1  reviews: total: 12  downloaded: 12  avg rating: 4.5        4.5
2    reviews: total: 17  downloaded: 17  avg rating: 4        4.0
3    reviews: total: 3  downloaded: 3  avg rating: 4.5        4.5
4  reviews: total: 15  downloaded: 15  avg rating: 4.5        4.5

In [163]:
def get_best_n_sellers(df, category, n=10):
    # Filter data by category
    category_df = df[df['Category'] == category]

    # Sort by AvgRating (highest first) and get top n
    top_sellers = category_df.nlargest(n, 'AvgRating')

    return top_sellers[['ProductID', 'Title', 'AvgRating']]

In [181]:
best_books = get_best_n_sellers(df, 'Book', 10)
print(best_books)

     ProductID  \
0   0771044445
6   0375709363
8   078510870X
16  0761116982
19  0312199406
26  0875420532
33  1571515429
35  B0000060T5
38  0811726371
40  0912500476

                                                                                                                                                           Title  \
0                                                                                                                        Patterns of Preaching: A Sermon Sampler
6                                                                                    Resetting the Clock : Five Anti-Aging Hormones That Improve and Extend Life
8                                                                             Computed Tomography : Fundamentals, System Technology, Image Quality, Applications
16                                                                                                                                Double Jeopardy (T*Witches, 6)
19                                                                                       Renovations: A Father and Son Rebuild a House and Rediscover Each Other
26                                                                                                 Baby Boomer Retirement: 65 Simple Ways to Protect Your Future
33  Experiencing and the Creation of Meaning: A Philosophical and Psychological Approach to the Subjective (Studies in Phenomenology and Existential Philosophy)
35                                                                                                        Power of Flowers: An Archetypal Journey Through Nature
38                                                                                                      In Quest of God: The Saga of an Extraordinary Pilgrimage
40                                                                                                                         Junie B. Jones Collection: Books 9-12

    AvgRating
0         5.0
6         5.0
8         5.0
16        5.0
19        5.0
26        5.0
33        5.0
35        5.0
38        5.0
40        5.0

In [182]:
print(df.columns)

Index(['value_product', 'ProductID', 'value_title', 'Title', 'value_category',
       'Category', 'value_rating', 'AvgRating'],
      dtype='object')

In [183]:

product_id = "0771044445"

product_reviews = df[df['ProductID'] == product_id]['value_rating'].str.extract(r'total: (\d+)')

print(f"Product {product_id} has {product_reviews.values[0][0]} reviews.")

Product 0771044445 has 2 reviews.

In [185]:
# Select movies with average rating >= 4.5
high_rated_movies = df[df['AvgRating'] >= 4.5]
print(high_rated_movies[['ProductID', 'Title', 'AvgRating']])

         ProductID  \
0       0771044445
1       0827229534
3       0486220125
4       B00000AU3R
6       0375709363
...            ...
273419  B00008MNUJ
273420  9700507734
273423  B000065AHM
273424  B000059TOC
273425  B00006JBIX

                                                                                                               Title  \
0                                                                            Patterns of Preaching: A Sermon Sampler
1                                                                                         Candlemas: Feast of Flames
3                                                                                                              Batik
4                                                                                                Losing Matt Shepard
6                                        Resetting the Clock : Five Anti-Aging Hormones That Improve and Extend Life
...                                                                                                              ...
273419  A Matter of Degrees: What Temperature Reveals About the Past and Future of Our Species, Planet, and Universe
273420                                                                                      Para alcanzar el orgasmo
273423                                                                                                     Lucky Man
273424                                                                                                   The Drifter
273425                                                                                         The House Of Morecock

        AvgRating
0             5.0
1             4.5
3             4.5
4             4.5
6             5.0
...           ...
273419        5.0
273420        5.0
273423        4.5
273424        5.0
273425        5.0

[124101 rows x 3 columns]

In [186]:
import pandas as pd

# Sample DataFrame (replace this with your actual data)
data = {
    'UserID': ['User1', 'User2', 'User1', 'User3', 'User2'],
    'ProductID': ['0771044445', '0771044445', '0827229534', '0771044445', '0486220125']
}

df = pd.DataFrame(data)

# Step 1: Find all users who purchased the same product
co_purchase_count = df.groupby('ProductID')['UserID'].nunique()

# Step 2: Display the number of customers co-purchasing each product
print(co_purchase_count)

ProductID
0486220125    1
0771044445    3
0827229534    1
Name: UserID, dtype: int64

In [187]:
import pandas as pd

data = {
    'UserID': ['User1', 'User2', 'User1', 'User3', 'User2'],
    'ProductID': ['0771044445', '0771044445', '0827229534', '0771044445', '0486220125']
}

df = pd.DataFrame(data)

co_purchase_count = df.groupby('ProductID')['UserID'].nunique()

print(co_purchase_count)

ProductID
0486220125    1
0771044445    3
0827229534    1
Name: UserID, dtype: int64

In [188]:
# For each product, find the users who co-purchased it
for product in co_purchase_count.index:
    print(f"Product {product} was co-purchased by the following users:")
    users_for_product = df[df['ProductID'] == product]['UserID'].unique()
    print(users_for_product)
    print()

Product 0486220125 was co-purchased by the following users:
['User2']

Product 0771044445 was co-purchased by the following users:
['User1' 'User2' 'User3']

Product 0827229534 was co-purchased by the following users:
['User1']